-- Eski fakt kartochkalariga flesh-karta savollarini yozish (425 ta).
--
-- MUAMMO. `question_uz` maydoni V49 dan keyin paydo bo'lgan, shu sababli undan
-- oldin qo'shilgan 425 ta kartochkada savol yo'q edi — ular flesh-kartalarda
-- umuman qatnashmasdi, ya'ni bazaning qariyb uchdan biri o'yindan tashqarida
-- qolgandi.
--
-- SAVOLLAR QAYERDAN. Har bir savol AYNAN o'sha kartochkaning fakt matnidan
-- kelib chiqadi: yangi fakt, sana yoki nom qo'shilmagan — javob doim
-- kartochkaning o'zida. Savollar uchinchi shaxsda («Amir Temur qachon
-- tug'ilgan?»), chunki flesh-kartada savolni bola o'qiydi, qahramon emas.
--
-- Tekshirildi: 425/425 kartochka qamrab olingan, kirill harfi yo'q, hammasi
-- «?» bilan tugaydi, ikkinchi shaxsda («sen», «siz») murojaat yo'q.

UPDATE fact_cards SET question_uz = $$Ahmad al-Farg'oniy qayerda tug'ilgan va qaysi asrda yashagan?$$ WHERE id = 181 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Ahmad al-Farg'oniyning ijodiy faoliyati qaysi shahar bilan bog'liq?$$ WHERE id = 182 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Ahmad al-Farg'oniy qaysi shaharlardagi rasadxona qurilishida qatnashgan?$$ WHERE id = 183 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Ahmad al-Farg'oniy kimning yulduzlar jadvalini tekshirib chiqqan?$$ WHERE id = 184 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Ahmad al-Farg'oniy qaysi yilgi quyosh tutilishini oldindan aytib bergan?$$ WHERE id = 185 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Ahmad al-Farg'oniy Yerning shakli haqida nimani ochib bergan?$$ WHERE id = 186 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Ahmad al-Farg'oniy Misrda qanday asbob yasagan?$$ WHERE id = 187 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Yevropaliklar Ahmad al-Farg'oniyni qanday nom bilan atashgan?$$ WHERE id = 188 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Ahmad al-Farg'oniyning nechta asari saqlanib qolgan?$$ WHERE id = 189 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Ahmad al-Farg'oniyning 1200 yilligi qachon nishonlangan?$$ WHERE id = 190 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Abu Nasr Forobiy qachon va qayerda tug'ilgan?$$ WHERE id = 191 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Nega Forobiyni «Ikkinchi muallim» deb atashgan?$$ WHERE id = 192 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Abu Nasr Forobiy qaysi shaharlarda o'qigan?$$ WHERE id = 193 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Abu Nasr Forobiy qaysi shaharlarda bo'lgan?$$ WHERE id = 194 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Abu Nasr Forobiy nechta tilni bilgan?$$ WHERE id = 195 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Abu Nasr Forobiy qaysi fanlar bilan shug'ullangan?$$ WHERE id = 196 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Forobiy nechta asar yozgan va nechtasi bizgacha yetib kelgan?$$ WHERE id = 197 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Musiqa ilmi Forobiy shug'ullangan fanlardan biri bo'lganmi?$$ WHERE id = 198 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Abu Nasr Forobiy qachon va qayerda vafot etgan?$$ WHERE id = 199 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Forobiyning nomi qaysi shahar nomidan olingan?$$ WHERE id = 200 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Cho'lponning asl ismi nima va u qayerda tug'ilgan?$$ WHERE id = 201 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Cho'lpon qanday maktablarda o'qigan?$$ WHERE id = 202 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Abdulhamid Sulaymon o'g'li ijodda qanday taxallus olgan?$$ WHERE id = 203 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Cho'lponning she'riy to'plamlari qanday nomlanadi?$$ WHERE id = 204 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Cho'lpon «Kecha va kunduz» romanini qachon yozgan?$$ WHERE id = 205 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Cho'lpon qanday hikoyalar yozgan?$$ WHERE id = 206 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Cho'lponning qanday sahna asarlari bor?$$ WHERE id = 207 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Cho'lpon qaysi adiblar bilan bir davrda ijod qilgan?$$ WHERE id = 208 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Cho'lpon qaysi yilda qatag'on qurboni bo'lgan?$$ WHERE id = 209 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Cho'lponning asarlari bugun qayerda o'qitiladi?$$ WHERE id = 210 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Abdulla Oripov qachon va qayerda tug'ilgan?$$ WHERE id = 211 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Abdulla Oripov qaysi universitetni tugatgan?$$ WHERE id = 212 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$O'zbekiston Davlat madhiyasi matnini kim yozgan?$$ WHERE id = 213 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Abdulla Oripovning qanday she'riy kitoblari bor?$$ WHERE id = 214 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Abdulla Oripov qanday dostonlar yozgan?$$ WHERE id = 215 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Abdulla Oripovning qaysi she'riy dramasi sahnalashtirilgan?$$ WHERE id = 216 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Abdulla Oripov qaysi shoirlarning asarlarini o'zbekchaga o'girgan?$$ WHERE id = 217 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Abdulla Oripov qachon O'zbekiston Qahramoni unvonini olgan?$$ WHERE id = 218 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Abdulla Oripov qanday davlat mukofotlari sovrindori bo'lgan?$$ WHERE id = 219 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Abdulla Oripov necha yoshida vafot etgan?$$ WHERE id = 220 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Erkin Vohidov qachon va qayerda tug'ilgan?$$ WHERE id = 221 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Erkin Vohidov qaysi universitetni tugatgan?$$ WHERE id = 222 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Erkin Vohidov qaysi nashriyotlarda muharrir bo'lib ishlagan?$$ WHERE id = 223 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Erkin Vohidov qaysi jurnalning bosh muharriri bo'lgan?$$ WHERE id = 224 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Erkin Vohidovning dastlabki to'plamlari qanday nomlanadi?$$ WHERE id = 225 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Erkin Vohidovning «Yoshlik devoni» kitobi qachon chiqqan?$$ WHERE id = 226 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Erkin Vohidovning keyingi kitoblari qanday nomlanadi?$$ WHERE id = 227 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Erkin Vohidov qanday sahna asarlarini yozgan?$$ WHERE id = 228 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Erkin Vohidov qachon O'zbekiston Qahramoni unvonini olgan?$$ WHERE id = 229 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Erkin Vohidov qachon va qayerda vafot etgan?$$ WHERE id = 230 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Mahmudxo'ja Behbudiy qachon va qayerda tug'ilgan?$$ WHERE id = 231 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Mahmudxo'ja Behbudiy qanday unvonlarga ega bo'lgan?$$ WHERE id = 232 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Mahmudxo'ja Behbudiy qaysi shaharlarda tatar ziyolilari bilan tanishgan?$$ WHERE id = 233 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Mahmudxo'ja Behbudiy qaysi nashrlarda maqolalar chop etgan?$$ WHERE id = 234 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Mahmudxo'ja Behbudiy qanday gazeta va jurnal ta'sis etgan?$$ WHERE id = 235 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Mahmudxo'ja Behbudiy qanday darsliklar yozgan?$$ WHERE id = 236 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Yangi o'zbek adabiyotining ilk drama asari qaysi?$$ WHERE id = 237 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$«Padarkush» dramasi birinchi marta qayerda sahnaga qo'yilgan?$$ WHERE id = 238 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Mahmudxo'ja Behbudiy qanday maktablarni targ'ib qilgan?$$ WHERE id = 239 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Mahmudxo'ja Behbudiy qachon va qayerda qatl etilgan?$$ WHERE id = 240 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Munavvarqori Abdurashidxonov qachon va qayerda tug'ilgan?$$ WHERE id = 241 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Munavvarqori Abdurashidxonov qaysi madrasada tahsil olgan?$$ WHERE id = 242 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Munavvarqori Abdurashidxonov qachon yangi usul maktabini ochgan?$$ WHERE id = 243 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$«Adibi avval» darsligi nimasi bilan mashhur?$$ WHERE id = 244 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Munavvarqori Abdurashidxonov yana qanday darsliklar yaratgan?$$ WHERE id = 245 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Munavvarqori Abdurashidxonov qanday gazeta tashkil etgan?$$ WHERE id = 246 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Munavvarqori Abdurashidxonov qaysi gazetada xizmat qilgan?$$ WHERE id = 247 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Turkiston xalq dorilfununining birinchi rektori kim bo'lgan?$$ WHERE id = 248 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Munavvarqori Abdurashidxonov maorif sohasida qanday lavozimlarda ishlagan?$$ WHERE id = 249 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Munavvarqori Abdurashidxonovning nomi qachon oqlangan?$$ WHERE id = 250 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Abdulla Avloniy qachon va qayerda tug'ilgan?$$ WHERE id = 251 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Abdulla Avloniy qaysi tillarni mustaqil o'rgangan?$$ WHERE id = 252 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Abdulla Avloniy qaysi gazetalarni chiqargan?$$ WHERE id = 253 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Abdulla Avloniy 1908-yilda Toshkentning qaysi mahallasida maktab ochgan?$$ WHERE id = 254 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Abdulla Avloniy 1909-yilda qanday jamiyat tuzgan?$$ WHERE id = 255 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Abdulla Avloniy qanday darsliklar yozgan?$$ WHERE id = 256 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Abdulla Avloniyning «Turkiy guliston yoxud axloq» kitobi nima haqida?$$ WHERE id = 257 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Abdulla Avloniy qachon teatr truppasini tuzgan?$$ WHERE id = 258 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Abdulla Avloniy qaysi mamlakatda siyosiy vakil bo'lib ishlagan?$$ WHERE id = 259 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Abdulla Avloniy umrining oxirida qayerda professor bo'lgan?$$ WHERE id = 260 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Abdurauf Fitrat qachon va qayerda tug'ilgan?$$ WHERE id = 261 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Fitrat taxallusi qanday ma'noni bildiradi?$$ WHERE id = 262 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Abdurauf Fitratning birinchi she'riy to'plami qanday nomlangan?$$ WHERE id = 263 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Abdurauf Fitratning «Munozara» asari nima haqida?$$ WHERE id = 264 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Abdurauf Fitrat qanday dramalar yozgan?$$ WHERE id = 265 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Abdurauf Fitrat til va adabiyot bo'yicha qanday asarlar yaratgan?$$ WHERE id = 266 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Abdurauf Fitrat qanday ilmiy unvonni birinchilardan bo'lib olgan?$$ WHERE id = 267 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Abdurauf Fitrat 1921-yilda qanday maktab tashkil etgan?$$ WHERE id = 268 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Abdurauf Fitratning musiqaga oid risolasi qanday nomlanadi?$$ WHERE id = 269 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Abdurauf Fitrat qaysi adiblar bilan birga qatag'on qurboni bo'lgan?$$ WHERE id = 270 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Oybekning asl ismi nima va u qayerda tug'ilgan?$$ WHERE id = 271 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Oybek qachondan she'r yoza boshlagan?$$ WHERE id = 272 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Oybekning ilk she'riy to'plamlari qanday nomlanadi?$$ WHERE id = 273 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Oybek «Qutlug' qon» romanini qachon yozgan?$$ WHERE id = 274 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Oybekning «Navoiy» romani qachon chiqqan?$$ WHERE id = 275 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Oybek yana qanday romanlar yozgan?$$ WHERE id = 276 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Oybekning «Bolalik» qissasi nima haqida?$$ WHERE id = 277 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Oybek qachon Fanlar akademiyasining haqiqiy a'zosi bo'lgan?$$ WHERE id = 278 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Oybek qaysi jahon adiblarining asarlarini tarjima qilgan?$$ WHERE id = 279 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Oybek qachon va qayerda vafot etgan?$$ WHERE id = 280 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Is'hoqxon Ibrat qachon va qayerda tug'ilgan?$$ WHERE id = 281 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Is'hoqxon Ibrat qaysi madrasada tahsil olgan?$$ WHERE id = 282 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Is'hoqxon Ibrat sayohatida qaysi shaharlarda bo'lgan?$$ WHERE id = 283 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Is'hoqxon Ibrat qaysi tillarni o'rgangan?$$ WHERE id = 284 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Is'hoqxon Ibrat qachon vatanga qaytib kelgan?$$ WHERE id = 285 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Is'hoqxon Ibratning olti tilli lug'ati qanday nomlanadi?$$ WHERE id = 286 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Is'hoqxon Ibrat qayerda yangi usul maktabini ochgan?$$ WHERE id = 287 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Is'hoqxon Ibrat qanday bosmaxona tashkil etgan?$$ WHERE id = 288 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Is'hoqxon Ibratning yozuvlar tarixiga oid asari qanday nomlanadi?$$ WHERE id = 289 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Is'hoqxon Ibrat necha yoshida vafot etgan?$$ WHERE id = 290 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Ubaydulla Xo'jayev qachon va qayerda tug'ilgan?$$ WHERE id = 291 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Ubaydulla Xo'jayev huquq ilmini qayerda o'rgangan?$$ WHERE id = 292 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Ubaydulla Xo'jayev advokatlik imtihonini qachon topshirgan?$$ WHERE id = 293 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Ubaydulla Xo'jayev nimasi bilan tarixda qolgan?$$ WHERE id = 294 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$«Sadoi Turkiston» gazetasi qachon chiqa boshlagan?$$ WHERE id = 295 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$«Sadoi Turkiston» gazetasi qachon yopilgan?$$ WHERE id = 296 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$«Sadoi Turkiston» sahifalarida kimlar qatnashgan?$$ WHERE id = 297 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Ubaydulla Xo'jayev 1917-yilda qaysi jamiyatga rais bo'lgan?$$ WHERE id = 298 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Ubaydulla Xo'jayev qaysi davlat qurilishida qatnashgan?$$ WHERE id = 299 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Ubaydulla Xo'jayev qachon va qayerda vafot etgan?$$ WHERE id = 300 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Anbar Otin qachon va qayerda tug'ilgan?$$ WHERE id = 301 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Anbar Otinning ota-onasi kim bo'lgan?$$ WHERE id = 302 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Anbar Otin kimning maktabida tahsil olgan?$$ WHERE id = 303 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Nega Anbar Otin «otin» deb atalgan?$$ WHERE id = 304 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Anbar Otin qaysi tillarda ijod qilgan?$$ WHERE id = 305 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Anbar Otin devonida nechta g'azal jamlangan?$$ WHERE id = 306 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Anbar Otin she'rlarining asosiy mavzusi nima?$$ WHERE id = 307 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Anbar Otin she'rlarida nimani ulug'lagan?$$ WHERE id = 308 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Anbar Otinning «Qarolar falsafasi» asari nima haqida?$$ WHERE id = 309 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Anbar Otin qachon va qayerda vafot etgan?$$ WHERE id = 310 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Zulfiya qachon va qayerda tug'ilgan?$$ WHERE id = 311 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Zulfiya she'r mashqlarini qayerda boshlagan?$$ WHERE id = 312 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Zulfiya qaysi institutda tahsil olgan?$$ WHERE id = 313 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Zulfiyaning birinchi she'riy to'plami qanday nomlanadi?$$ WHERE id = 314 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Zulfiyaning qanday to'plamlari nashr etilgan?$$ WHERE id = 315 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Zulfiya kimning dostonlari asosida opera librettolarini yaratgan?$$ WHERE id = 316 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Zulfiyaning «Mushoira» asari qanday safar ta'sirida tug'ilgan?$$ WHERE id = 317 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Zulfiya qanday xalqaro mukofotlarni olgan?$$ WHERE id = 318 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Zulfiyaning she'rlari qaysi tillarga tarjima qilingan?$$ WHERE id = 319 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Zulfiya necha yoshida vafot etgan?$$ WHERE id = 320 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$G'afur G'ulom qachon va qayerda tug'ilgan?$$ WHERE id = 321 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$G'afur G'ulom «Shum bola» qissasini qachon yozgan?$$ WHERE id = 322 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$G'afur G'ulomning qanday she'riy to'plamlari chiqqan?$$ WHERE id = 323 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$G'afur G'ulomning qaysi she'rlari keng tanilgan?$$ WHERE id = 324 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$G'afur G'ulom qanday qissalar yozgan?$$ WHERE id = 325 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$G'afur G'ulom «Mening o'g'rigina bolam» hikoyasini qachon yozgan?$$ WHERE id = 326 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$G'afur G'ulom qachon Fanlar akademiyasining haqiqiy a'zosi bo'lgan?$$ WHERE id = 327 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$G'afur G'ulom qanday ilmiy maqolalar yozgan?$$ WHERE id = 328 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$G'afur G'ulom Shekspirning qaysi asarlarini o'zbekchaga o'girgan?$$ WHERE id = 329 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$G'afur G'ulom qachon vafot etgan?$$ WHERE id = 330 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Ali Qushchi qachon tug'ilgan va qayerda voyaga yetgan?$$ WHERE id = 331 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Ali Qushchining laqabi nima bilan bog'liq?$$ WHERE id = 332 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Ali Qushchi Ulug'bek davrasida qaysi olimlar bilan ishlagan?$$ WHERE id = 333 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Ali Qushchi qachon Ulug'bek madrasasida ilk ma'ruza o'qigan?$$ WHERE id = 334 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Ulug'bek Ali Qushchini nima uchun Xitoyga yuborgan?$$ WHERE id = 335 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Ali Qushchining «Ziji jadidi Ko'ragoniy»ni yakunlashdagi hissasi qanday bo'lgan?$$ WHERE id = 336 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Ali Qushchini qanday unvon bilan atashgan?$$ WHERE id = 337 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Ali Qushchi qaysi tillarda ilmiy asarlar yaratgan?$$ WHERE id = 338 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Ali Qushchi tarixda kim sifatida qolgan?$$ WHERE id = 339 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Ulug'bek G'iyosiddin Jamshid Koshiyni qachon Samarqandga chaqirgan?$$ WHERE id = 340 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$G'iyosiddin Jamshid Koshiy Samarqand rasadxonasi qurilishida qanday rol o'ynagan?$$ WHERE id = 341 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$G'iyosiddin Jamshid Koshiy Ulug'bek davrasida kimlar bilan ishlagan?$$ WHERE id = 342 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Koshiy «Miftoh ul-hisob» asarini qachon yakunlagan?$$ WHERE id = 343 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$G'iyosiddin Jamshid Koshiy Ulug'bek uchun kim bo'lgan?$$ WHERE id = 344 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$G'iyosiddin Jamshid Koshiy qachon vafot etgan?$$ WHERE id = 345 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Koshiyning ishlari qaysi fan rivojiga xizmat qilgan?$$ WHERE id = 346 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Husayn Boyqaro qachon va qayerda tug'ilgan?$$ WHERE id = 347 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Husayn Boyqaro qaysi yildan Xuroson taxtini boshqargan?$$ WHERE id = 348 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Husayn Boyqaro Xurosonni necha yil boshqargan?$$ WHERE id = 349 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Husayn Boyqaro she'rlarini qanday taxallus bilan yozgan?$$ WHERE id = 350 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Husayn Boyqaro devoniga nechta g'azal kirgan?$$ WHERE id = 351 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Husayn Boyqaro Alisher Navoiyni qaysi lavozimga tayinlagan?$$ WHERE id = 352 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Husayn Boyqaro davrida Hirot qanday shaharga aylangan?$$ WHERE id = 353 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Husayn Boyqaro qanday binolar qurdirgan?$$ WHERE id = 354 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Husayn Boyqaro qaysi musavvirga miniatyura yaratishni topshirgan?$$ WHERE id = 355 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Husayn Boyqaro qachon vafot etgan va qayerga dafn qilingan?$$ WHERE id = 356 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Kamoliddin Behzod qachon tug'ilgan va qachon vafot etgan?$$ WHERE id = 357 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Kamoliddin Behzod necha yoshida Hirot miniatyura maktabining yetakchisi bo'lgan?$$ WHERE id = 358 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Kamoliddin Behzodni qanday nom bilan atashadi?$$ WHERE id = 359 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Kamoliddin Behzod kimlarning portretlarini chizgan?$$ WHERE id = 360 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Kamoliddin Behzod Sharq miniatyurasida qaysi janrning ustasi sanaladi?$$ WHERE id = 361 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Qaysi hukmdor Behzodga miniatyura yaratishni topshirgan?$$ WHERE id = 362 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Behzod «Rassom portreti» asarini qachon yaratgan?$$ WHERE id = 363 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Behzodning qaysi portreti G'arb olimlari tomonidan o'rganilgan?$$ WHERE id = 364 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Kamoliddin Behzodning ishlari qanday e'tirof etiladi?$$ WHERE id = 365 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Saroymulkxonimning otasi kim bo'lgan?$$ WHERE id = 366 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Amir Temur Saroymulkxonimga qachon uylangan?$$ WHERE id = 367 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Temur nima uchun «Ko'ragon» unvonini olgan?$$ WHERE id = 368 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Saroymulkxonim el ichida qanday nom bilan tanilgan?$$ WHERE id = 369 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Saroymulkxonim davlat ishlarida qanday qatnashgan?$$ WHERE id = 370 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Saroymulkxonim Samarqandda nima qurdirgan?$$ WHERE id = 371 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Temur nabiralarining tarbiyasini kimga ishongan?$$ WHERE id = 372 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Bibixonim masjidi qaysi yillarda qurilgan?$$ WHERE id = 373 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Saroymulkxonim qachon vafot etgan va qayerga dafn qilingan?$$ WHERE id = 374 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Gavharshod begimning otasi kim bo'lgan?$$ WHERE id = 375 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Gavharshod begim kimga turmushga chiqqan?$$ WHERE id = 376 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Gavharshod begimning mashhur o'g'illari kimlar?$$ WHERE id = 377 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Shohrux ilm bilan band bo'lganda saltanat ishlarini kim boshqargan?$$ WHERE id = 378 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Gavharshod begim davlat boshqaruvida qanday ishlarda qatnashgan?$$ WHERE id = 379 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Gavharshod begim Hirotda nechta madrasa qurdirgan?$$ WHERE id = 380 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Gavharshod begim madrasadan tashqari yana qanday binolar qurdirgan?$$ WHERE id = 381 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Gavharshod begimning umri qanday yakunlangan?$$ WHERE id = 382 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Gavharshod begim qayerga dafn qilingan?$$ WHERE id = 383 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Nodiraning asl ismi nima va otasi kim bo'lgan?$$ WHERE id = 384 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Nodira kimga turmushga chiqqan?$$ WHERE id = 385 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Umarxon vafotidan keyin davlatni kim idora qilgan?$$ WHERE id = 386 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Nodira qaysi shoirani saroyga ustoz qilib chaqirgan?$$ WHERE id = 387 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Nodira qanday binolar qurdirgan?$$ WHERE id = 388 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Nodira she'rlarini qanday taxalluslar bilan yozgan?$$ WHERE id = 389 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Nodira devonida nechta she'r jamlangan?$$ WHERE id = 390 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Nodira saroyida shoiralarga qanday munosabatda bo'lgan?$$ WHERE id = 391 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Nodira qanday sharoitda halok bo'lgan?$$ WHERE id = 392 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Uvaysiyning asl ismi nima va u qayerda tug'ilgan?$$ WHERE id = 393 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Uvaysiy she'riyat ilmini kimdan o'rgangan?$$ WHERE id = 394 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Uvaysiy ta'lim sohasida nima bilan shug'ullangan?$$ WHERE id = 395 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Uvaysiy Qo'qon saroyida kimga ustozlik qilgan?$$ WHERE id = 396 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Uvaysiy qanday she'riy topishmoqlar yozgan?$$ WHERE id = 397 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Uvaysiy nechta g'azal yozgan?$$ WHERE id = 398 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Uvaysiyning dostonlari qanday nomlanadi?$$ WHERE id = 399 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Dilshod otin ma'lumotiga ko'ra, Uvaysiy qaysi shaharlarda bo'lgan?$$ WHERE id = 400 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Uvaysiy umrining oxirini qayerda o'tkazgan?$$ WHERE id = 401 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Abulg'ozi Bahodirxonning otasi kim bo'lgan?$$ WHERE id = 402 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Abulg'ozi Bahodirxon qaysi yildan Xiva xonligini boshqargan?$$ WHERE id = 403 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Abulg'ozi Bahodirxon Xivani necha yil boshqargan?$$ WHERE id = 404 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Abulg'ozi Bahodirxonning «Shajarai turk» asari nima haqida?$$ WHERE id = 405 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Olimlar «Shajarai turk» asaridan qanday maqsadda foydalanadilar?$$ WHERE id = 406 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Abulg'ozi Bahodirxon davlat arbobidan tashqari yana kim sifatida tanilgan?$$ WHERE id = 407 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Abulg'ozi Bahodirxon qachon vafot etgan?$$ WHERE id = 408 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Munis Xorazmiy qachon va qayerda tug'ilgan?$$ WHERE id = 409 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Munis Xorazmiy saroyda qanday vazifada ishlagan?$$ WHERE id = 410 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Munis Xorazmiy ilk she'riy devonini qachon tuzgan?$$ WHERE id = 411 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Munis Xorazmiyning savod o'rgatishga oid risolasi qanday nomlanadi?$$ WHERE id = 412 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Munis Xorazmiy kimning topshirig'i bilan «Firdavs ul-iqbol»ni yozgan?$$ WHERE id = 413 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$«Munis ul-ushshoq» devoniga nechta misra she'r jamlangan?$$ WHERE id = 414 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Munis Xorazmiy kimning asarini turkiyga tarjima qilgan?$$ WHERE id = 415 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Munis Xorazmiyning tugallanmagan ishlarini kim yakunlagan?$$ WHERE id = 416 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Munis Xorazmiy qachon vafot etgan?$$ WHERE id = 417 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Ogahiy qachon va qayerda tug'ilgan?$$ WHERE id = 418 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Ogahiy qaysi tillarni o'rgangan?$$ WHERE id = 419 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Ogahiy kimning o'rniga mirob etib tayinlangan?$$ WHERE id = 420 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Ogahiy nima sababdan miroblikdan iste'foga chiqqan?$$ WHERE id = 421 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Ogahiy qanday tarixiy asarlar yozgan?$$ WHERE id = 422 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Ogahiy asarlarida qaysi xalqlar tarixini bayon qilgan?$$ WHERE id = 423 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Ogahiy tog'asi Munisning qaysi ishlarini yakunlagan?$$ WHERE id = 424 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Ogahiy xotirasiga Qiyotda nima tashkil etilgan?$$ WHERE id = 425 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Ogahiy qachon vafot etgan?$$ WHERE id = 426 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Boborahim Mashrab qachon va qayerda tug'ilgan?$$ WHERE id = 427 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Boborahim Mashrab diniy ilm va tasavvufni kimdan o'rgangan?$$ WHERE id = 428 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Boborahim Mashrab kimning xizmatiga borgan?$$ WHERE id = 429 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Boborahim Mashrab she'rlarining katta qismi qayerda yaratilgan?$$ WHERE id = 430 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Boborahim Mashrabning umri qanday o'tgan?$$ WHERE id = 431 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Boborahim Mashrabning she'rlari xalq orasida qanday tarqalgan?$$ WHERE id = 432 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Boborahim Mashrabning nomi qanday asarlarda tilga olingan?$$ WHERE id = 433 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Boborahim Mashrab qachon va qayerda vafot etgan?$$ WHERE id = 434 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Muhammad Rahimxon Feruz qachon va qayerda tug'ilgan?$$ WHERE id = 435 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Muhammad Rahimxon Feruz qachon Xiva taxtiga o'tirgan?$$ WHERE id = 436 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Muhammad Rahimxon she'rlarini qanday taxallus bilan yozgan?$$ WHERE id = 437 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$«Devoni Feruz» to'plami qachon tuzilgan?$$ WHERE id = 438 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Feruzning ustozi kim bo'lgan?$$ WHERE id = 439 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Feruz Xivada ochgan toshbosmada qanday kitoblar bosilgan?$$ WHERE id = 440 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Feruz musiqa sohasida nimani qo'llab-quvvatlagan?$$ WHERE id = 441 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Feruz qachon o'z nomi bilan ataluvchi madrasa qurdirgan?$$ WHERE id = 442 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Muhammad Rahimxon Feruz qachon vafot etgan?$$ WHERE id = 443 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Somoniylar sulolasi kimning nomi bilan atalgan?$$ WHERE id = 444 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Ismoil Somoniy qaysi yildan Movarounnahr noibi bo'lgan?$$ WHERE id = 445 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Ismoil Somoniy 893-yilda qaysi shaharga yurish qilgan?$$ WHERE id = 446 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Ismoil Somoniy tuzgan davlatning poytaxti qaysi shahar edi?$$ WHERE id = 447 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Ismoil Somoniy Xuroson uchun kurashda kimlar ustidan g'alaba qozongan?$$ WHERE id = 448 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Zamondoshlari Ismoil Somoniyni qanday hukmdor deb bilishgan?$$ WHERE id = 449 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$«Amiri moziy» laqabi nimani anglatadi?$$ WHERE id = 450 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Narshaxiy yozishicha, Ismoil Somoniy necha yil hukmronlik qilgan?$$ WHERE id = 451 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Ismoil Somoniy qachon va qayerda vafot etgan?$$ WHERE id = 452 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Muqannaning asl ismi nima?$$ WHERE id = 453 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Nega Hoshim ibn Hakim «Muqanna» deb atalgan?$$ WHERE id = 454 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Narshaxiy Muqanna haqida nima deb yozgan?$$ WHERE id = 455 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Muqanna Xurosonda qanday darajaga ko'tarilgan?$$ WHERE id = 456 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$«Oq kiyimlilar» qo'zg'oloni qaysi yillarda bo'lgan?$$ WHERE id = 457 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Muqanna qaysi qal'ani o'ziga qarorgoh qilgan?$$ WHERE id = 458 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Muqanna qo'zg'oloni qaysi hududlarda avj olgan?$$ WHERE id = 459 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Muqanna qanday ta'limotni targ'ib qilgan?$$ WHERE id = 460 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$775-yilda xalifa Mansur qo'shini bilan nima bo'lgan?$$ WHERE id = 461 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Muqanna haqida qaysi adiblar asar yozgan?$$ WHERE id = 462 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Abu Bakr Narshaxiyning nisbasi qaysi qishloq nomidan olingan?$$ WHERE id = 463 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Narshaxiyning to'la ismi qaysi asarda saqlanib qolgan?$$ WHERE id = 464 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Narshaxiy «Buxoro tarixi» kitobini qachon va qaysi tilda yozgan?$$ WHERE id = 465 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Narshaxiy kitobini qaysi hukmdorga bag'ishlagan?$$ WHERE id = 466 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Narshaxiyning «Buxoro tarixi» asarida nimalar haqida hikoya qilinadi?$$ WHERE id = 467 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Narshaxiy kitobida qaysi qo'zg'olon haqida batafsil yozgan?$$ WHERE id = 468 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Narshaxiyning kitobini kim fors tiliga tarjima qilgan?$$ WHERE id = 469 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Narshaxiyning forscha tarjimasini kim qayta qisqartirib bayon qilgan?$$ WHERE id = 470 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Narshaxiyning kitobi yana qanday nomlar bilan mashhur bo'lgan?$$ WHERE id = 471 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Narshaxiyning kitobi qaysi shaharlarda nashr etilgan?$$ WHERE id = 472 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$To'maris qaysi xalqning malikasi bo'lgan?$$ WHERE id = 473 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Massagetlar qayerda yashagan?$$ WHERE id = 474 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$To'maris qanday sharoitda xalqiga boshchilik qila boshlagan?$$ WHERE id = 475 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Kir II qachon massagetlar ustiga yurish qilgan?$$ WHERE id = 476 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$To'maris Kir II ga qanday taklif bergan?$$ WHERE id = 477 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$To'maris haqidagi voqealarni kim yozib qoldirgan?$$ WHERE id = 478 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Gerodot massagetlar bilan bo'lgan jangni qanday ta'riflagan?$$ WHERE id = 479 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Kir II ning taqdiri qanday yakunlangan?$$ WHERE id = 480 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$To'marisning nomi bugun nimaning ramzi?$$ WHERE id = 481 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Shiroq qaysi qabiladan chiqqan va kim bo'lgan?$$ WHERE id = 482 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Behistun bitiklarida saklar qanday ta'riflangan?$$ WHERE id = 483 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Qaysi fors shohi saklar yurtiga qo'shin tortgan?$$ WHERE id = 484 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Shiroq forslar qoshiga qanday qiyofada borgan?$$ WHERE id = 485 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Shiroq dushman qo'shinini qayerga boshlab borgan?$$ WHERE id = 486 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Forslar sahroda necha kun yo'l bosgan?$$ WHERE id = 487 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Shiroq vatani uchun nima qilgan?$$ WHERE id = 488 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Shiroqning jasorati qanday natijaga olib kelgan?$$ WHERE id = 489 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Shiroq haqidagi rivoyatni kim yozib qoldirgan?$$ WHERE id = 490 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Zardusht qaysi dinning asoschisi?$$ WHERE id = 491 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Zardusht qaysi davrda yashagan?$$ WHERE id = 492 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Olimlar «Avesto»ning eng qadimgi qismlari qayerda vujudga kelgan deb hisoblaydi?$$ WHERE id = 493 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Rivoyatga ko'ra, Zardusht necha yoshida payg'ambarga aylangan?$$ WHERE id = 494 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Zardusht ta'limotining uchta bosh qoidasi nima?$$ WHERE id = 495 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Zardushtiylikda qaysi unsurlar muqaddas sanalgan?$$ WHERE id = 496 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$«Avesto» nomi qanday ma'noni anglatadi?$$ WHERE id = 497 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$«Avesto» matnlari nechta kitobga jamlangan?$$ WHERE id = 498 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Yunonlar Zardushtni qanday nom bilan atashgan?$$ WHERE id = 499 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Navro'z bayramining ildizlari qaysi davrga borib taqaladi?$$ WHERE id = 500 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Spitamen kim bo'lgan?$$ WHERE id = 501 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Iskandar Maqduniy qachon Movarounnahrga bostirib kirgan?$$ WHERE id = 502 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Yunon-makedon qo'shinlari egallagan Maroqanda hozir qaysi shahar?$$ WHERE id = 503 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Spitamen qo'zg'olonda qaysi xalqlarni birlashtirgan?$$ WHERE id = 504 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Spitamen qaysi shaharni qamal qilgan?$$ WHERE id = 505 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Spitamen Politimet bo'yida qanday g'alaba qozongan?$$ WHERE id = 506 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Spitamen boshchiligidagi qarshilik necha yil davom etgan?$$ WHERE id = 507 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Spitamen Iskandarning sulh taklifiga qanday javob bergan?$$ WHERE id = 508 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Spitamen qachon va qanday halok bo'lgan?$$ WHERE id = 509 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Spitamenning qizi kimga turmushga chiqqan?$$ WHERE id = 510 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Kanishka qaysi podsholikning hukmdori bo'lgan?$$ WHERE id = 511 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Kushon davlati qaysi asrlarda hukm surgan?$$ WHERE id = 512 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Kanishka poytaxtni qaysi shaharga ko'chirgan?$$ WHERE id = 513 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Kushon davlati hududiga qaysi yerlar kirgan?$$ WHERE id = 514 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Kushon davlati qaysi buyuk davlatlar qatorida turgan?$$ WHERE id = 515 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Kanishka davrida qaysi davlatlar bilan savdo yo'lga qo'yilgan?$$ WHERE id = 516 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Yurtimizga buddaviylik dini qanday kirib kelgan?$$ WHERE id = 517 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Termiz atrofidagi qaysi ibodatxonalar buddaviylikdan guvohlik beradi?$$ WHERE id = 518 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Kushon podsholigining dastlabki poytaxti qayer bo'lgan?$$ WHERE id = 519 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Kushon podsholigida qanday metallardan tanga zarb qilingan?$$ WHERE id = 520 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Bumin xoqon qaysi davlatga asos solgan?$$ WHERE id = 521 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Bumin xoqon qaysi hududdagi turkiy qabilalarni birlashtirgan?$$ WHERE id = 522 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Bumin xoqon qaysi yilda «xoqon» deb e'lon qilingan?$$ WHERE id = 523 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$«Xoqon» so'zi qanday ma'noni anglatadi?$$ WHERE id = 524 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Turk xoqonligining markazi qayer bo'lgan?$$ WHERE id = 525 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$555-yilda turklar qaysi o'lkalarni egallagan?$$ WHERE id = 526 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Turklarning g'arbga yurishlariga kim boshchilik qilgan?$$ WHERE id = 527 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Turk xoqonligi nechta davlatga bo'linib ketgan?$$ WHERE id = 528 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Istami xoqon Turk xoqonligida nimaga boshchilik qilgan?$$ WHERE id = 529 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Istami xoqonga qanday unvon berilgan?$$ WHERE id = 530 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Istami xoqon yurishlari natijasida qaysi yurtlar bo'ysundirilgan?$$ WHERE id = 531 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$555-yilda turklar qaysi hududlarni egallagan?$$ WHERE id = 532 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Istami xoqon qaysi davlat bilan harbiy ittifoq tuzgan?$$ WHERE id = 533 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$563-yilda turk qo'shinlari qaysi shaharlarni egallagan?$$ WHERE id = 534 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Eftallar davlati barham topgach, qaysi yerlar Turk xoqonligiga o'tgan?$$ WHERE id = 535 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Turklar Buyuk ipak yo'lida kim bilan savdo qilgan?$$ WHERE id = 536 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Tamara Xonimning asl ismi nima va u qayerda tug'ilgan?$$ WHERE id = 537 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$1920-yildagi ansamblda nechta ayol bor edi?$$ WHERE id = 538 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Tamara Xonimga qanday ta'rif berilgan?$$ WHERE id = 539 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Tamara Xonim ustozi bilan qanday darslik yaratgan?$$ WHERE id = 540 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Tamara Xonim qaysi teatrda raqs truppasini boshqargan?$$ WHERE id = 541 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Tamara Xonim qaysi shahardagi festivalda oltin medal olgan?$$ WHERE id = 542 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Tamara Xonim urush yillarida nima qilgan?$$ WHERE id = 543 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Tamara Xonimning ijodiy xazinasi nechta millat qo'shig'i bilan boyigan?$$ WHERE id = 544 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Tamara Xonimning xotira muzeyi qachon tashkil etilgan?$$ WHERE id = 545 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Tamara Xonimning 120 yilligi qayerda nishonlangan?$$ WHERE id = 546 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Halima Nosirova qachon va qayerda tug'ilgan?$$ WHERE id = 547 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Halima Nosirova qaysi shahardagi teatr bilim yurtiga yuborilgan?$$ WHERE id = 548 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Halima Nosirova opera san'atini qayerda o'rgangan?$$ WHERE id = 549 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Halima Nosirova «Halima» spektaklida bosh rolni necha marta ijro etgan?$$ WHERE id = 550 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Birinchi o'zbek operasi qanday nomlangan va qachon sahnaga qo'yilgan?$$ WHERE id = 551 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Halima Nosirova qaysi operalarda bosh obrazlarni yaratgan?$$ WHERE id = 552 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Halima Nosirova qanday xalq ashulalarini kuylagan?$$ WHERE id = 553 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Halima Nosirova urush yillarida nima qilgan?$$ WHERE id = 554 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Halima Nosirova qaysi filmlarda rol o'ynagan?$$ WHERE id = 555 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Halima Nosirovaning xotira kitobi qanday nomlanadi?$$ WHERE id = 556 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Zebo G'aniyeva qachon tug'ilgan?$$ WHERE id = 557 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Zebo G'aniyeva Toshkentda qaysi bo'limga o'qishga kirgan?$$ WHERE id = 558 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Zebo G'aniyeva 1940-yilda qayerda o'qigan?$$ WHERE id = 559 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Zebo G'aniyeva urush boshlanganida nima qilgan?$$ WHERE id = 560 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Zebo G'aniyeva frontda qanday nom qozongan?$$ WHERE id = 561 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Zebo G'aniyeva jangda qanday jarohat olgan?$$ WHERE id = 562 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Zebo G'aniyeva qaysi filmda rol o'ynagan?$$ WHERE id = 563 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Zebo G'aniyeva urushdan keyin qanday faoliyat ko'rsatgan?$$ WHERE id = 564 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Zebo G'aniyevani hayotligidayoq qanday atashgan?$$ WHERE id = 565 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Mukarrama Turg'unboyeva qachon va qayerda tug'ilgan?$$ WHERE id = 566 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Mukarrama Turg'unboyeva kimning raqsini ko'rib san'atkor bo'lishga ahd qilgan?$$ WHERE id = 567 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Mukarrama Turg'unboyeva o'zbek raqsini kimlardan o'rgangan?$$ WHERE id = 568 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Mukarrama Turg'unboyevaning qaysi qo'llanmasi asosida o'zbek raqsi o'qitiladi?$$ WHERE id = 569 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Mukarrama Turg'unboyeva qaysi raqsning ilk ijrochisi bo'lgan?$$ WHERE id = 570 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Mukarrama Turg'unboyevada qizlar ansambli tuzish orzusi qanday paydo bo'lgan?$$ WHERE id = 571 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$«Bahor» ansambli qachon tuzilgan va nomi qayerdan olingan?$$ WHERE id = 572 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Mukarrama Turg'unboyeva nechta raqs sahnalashtirgan?$$ WHERE id = 573 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Mukarrama Turg'unboyeva xotirasiga qanday tanlov o'tkaziladi?$$ WHERE id = 574 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$«Bahor» davlat raqs ansambli qachon qayta tashkil etilgan?$$ WHERE id = 575 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Halima Xudoyberdiyeva qachon va qayerda tug'ilgan?$$ WHERE id = 576 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Halima Xudoyberdiyevaning ilk she'rlari qachon bosilgan?$$ WHERE id = 577 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Halima Xudoyberdiyeva qaysi universitetni tugatgan?$$ WHERE id = 578 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Halima Xudoyberdiyevaning birinchi she'riy kitobi qanday nomlanadi?$$ WHERE id = 579 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Halima Xudoyberdiyeva qaysi jurnalga bosh muharrirlik qilgan?$$ WHERE id = 580 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Halima Xudoyberdiyeva qaysi qo'mitaga raislik qilgan?$$ WHERE id = 581 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Halima Xudoyberdiyevaning jasur ayollarga bag'ishlangan kitobi qanday nomlanadi?$$ WHERE id = 582 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Halima Xudoyberdiyeva qachon xalq shoiri unvonini olgan?$$ WHERE id = 583 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Halima Xudoyberdiyeva 2017-yilda qanday orden bilan taqdirlangan?$$ WHERE id = 584 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Halima Xudoyberdiyeva nomidagi ijod maktabi qayerda tashkil etilgan?$$ WHERE id = 585 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Dilbar Abdurahmonova qachon va qayerda tug'ilgan?$$ WHERE id = 586 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Dilbar Abdurahmonova qaysi musiqa asbobi bo'yicha o'qigan?$$ WHERE id = 587 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Dilbar Abdurahmonova dirijyorlikni kimning sinfida o'rgangan?$$ WHERE id = 588 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Dilbar Abdurahmonova talabalik yillarida qaysi teatr orkestrida chalgan?$$ WHERE id = 589 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$O'zbekistonda dirijyorlik pultiga chiqqan birinchi ayol kim?$$ WHERE id = 590 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Dilbar Abdurahmonova qaysi yillarda Navoiy teatrining bosh dirijyori bo'lgan?$$ WHERE id = 591 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Dilbar Abdurahmonova qaysi baletni sahnalashtirgani uchun mukofot olgan?$$ WHERE id = 592 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Dilbar Abdurahmonova qachon SSSR xalq artisti bo'lgan?$$ WHERE id = 593 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Dilbar Abdurahmonova qayerda professor bo'lib dars bergan?$$ WHERE id = 594 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Dilbar Abdurahmonova qachon vafot etgan?$$ WHERE id = 595 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Ozod Sharafiddinov qachon va qayerda tug'ilgan?$$ WHERE id = 596 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Ozod Sharafiddinov qachon professor unvonini olgan?$$ WHERE id = 597 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Ozod Sharafiddinov necha yil universitetda dars bergan?$$ WHERE id = 598 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Ozod Sharafiddinovning ilk mashhur kitobi qanday nomlanadi?$$ WHERE id = 599 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Ozod Sharafiddinov «Cho'lponni anglash» asarida nima qilgan?$$ WHERE id = 600 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Ozod Sharafiddinov qaysi jahon adiblarini o'zbekchaga tarjima qilgan?$$ WHERE id = 601 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Ozod Sharafiddinov qaysi jurnalga bosh muharrirlik qilgan?$$ WHERE id = 602 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Ozod Sharafiddinov qachon Beruniy nomidagi davlat mukofotini olgan?$$ WHERE id = 603 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Ozod Sharafiddinov qachon O'zbekiston Qahramoni unvonini olgan?$$ WHERE id = 604 AND question_uz IS NULL;
UPDATE fact_cards SET question_uz = $$Ozod Sharafiddinov qachon va qayerda vafot etgan?$$ WHERE id = 605 AND question_uz IS NULL;
