-- Tirik tarix: boshlang'ich kontent.
-- Barcha faktlar tarixiy manbalarga tayanadi va metodist tekshiruvidan o'tishi shart.
-- MVP: 3 qahramon, 8 davr, voqealar lentasi, fakt kartochkalari va savollar banki.

-- ============ DAVRLAR (kontseptsiyadagi 8 davr) ============

INSERT INTO eras (code, name_uz, ordinal, year_from, year_to, description_uz) VALUES
('qadimgi',     $$Qadimgi davr$$,      1, -3000, -330, $$Eng qadimgi odamlardan ilk davlatlargacha: «Avesto», Katta Xorazm, Baqtriya va So'g'diyona.$$),
('antik',       $$Antik davr$$,        2, -329,  600,  $$Iskandar yurishi, Kushon saltanati va Buyuk ipak yo'lining gullab-yashnashi.$$),
('arab',        $$Arablar davri$$,     3, 651,   999,  $$Islom dinining kirib kelishi va Movarounnahr olimlarining oltin asri.$$),
('temuriylar',  $$Temuriylar davri$$,  4, 1370,  1506, $$Amir Temur saltanati va temuriylar Uyg'onish davri: ilm-fan, me'morlik, adabiyot.$$),
('xonliklar',   $$Xonliklar davri$$,   5, 1506,  1865, $$Buxoro, Xiva va Qo'qon davlatlari davri.$$),
('jadidlar',    $$Jadidlar davri$$,    6, 1865,  1917, $$Mustamlaka zulmiga qarshi ma'rifat harakati: yangi usul maktablari, teatr, matbuot.$$),
('xx-asr',      $$XX asr$$,            7, 1917,  1991, $$Turkiston muxtoriyatidan mustaqillik arafasigacha bo'lgan murakkab davr.$$),
('mustaqillik', $$Mustaqillik davri$$, 8, 1991,  NULL, $$1991-yil 31-avgustdan boshlangan yangi tarix.$$);

-- ============ QAHRAMONLAR ============

INSERT INTO heroes (slug, name_uz, title_uz, birth_year, death_year, era_id, bio_uz, greeting_uz, portrait_emoji, on_topic_keywords) VALUES
('amir-temur', $$Amir Temur$$, $$Sohibqiron$$, 1336, 1405,
 (SELECT id FROM eras WHERE code = 'temuriylar'),
 $$Buyuk sarkarda va davlat arbobi. 1370-yilda Movarounnahrda markazlashgan davlatga asos solgan, poytaxti — Samarqand.$$,
 $$Assalomu alaykum, farzandim! Men Amir Temur — Sohibqironman. Mendan davlatim, yurishlarim, Samarqand va tuzuklarim haqida so'ra!$$,
 $$⚔️$$,
 $$["temur", "temurbek", "sohibqiron", "amir"]$$),
('mirzo-ulugbek', $$Mirzo Ulug'bek$$, $$Olim podshoh$$, 1394, 1449,
 (SELECT id FROM eras WHERE code = 'temuriylar'),
 $$Buyuk astronom va davlat arbobi, Amir Temurning nabirasi. Samarqandda rasadxona qurdirib, 1018 yulduz jadvalini tuzgan.$$,
 $$Assalomu alaykum, aziz farzand! Men Mirzo Ulug'bekman. Mendan yulduzlar, rasadxonam, madrasalarim va ilm-fan haqida so'ra!$$,
 $$🔭$$,
 $$["ulugbek", "mirzo", "muhammad taragay"]$$),
('alisher-navoiy', $$Alisher Navoiy$$, $$Nizomiddin Mir Alisher$$, 1441, 1501,
 (SELECT id FROM eras WHERE code = 'temuriylar'),
 $$Buyuk shoir va mutafakkir, o'zbek adabiy tilining asoschisi. «Xamsa» va «Xazoyin ul-maoniy» muallifi.$$,
 $$Assalomu alaykum, aziz do'stim! Men Alisher Navoiyman. Mendan she'rlarim, «Xamsa», ona tilimiz va Hirot haqida so'ra!$$,
 $$📜$$,
 $$["navoiy", "alisher", "foniy"]$$);

-- ============ FAKT KARTOCHKALARI: AMIR TEMUR ============

INSERT INTO fact_cards (hero_id, topic_uz, fact_uz, keywords, source) VALUES
((SELECT id FROM heroes WHERE slug = 'amir-temur'), $$Tug'ilishi$$,
 $$Men 1336-yil 9-aprelda Kesh (hozirgi Shahrisabz) yaqinidagi Xo'ja Ilg'or qishlog'ida tug'ilganman. Otam — barlos beklaridan Amir Tarag'ay.$$,
 $$["tugil", "kesh", "shahrisabz", "otang", "taragay", "bolalik", "qayerlik"]$$,
 $$O'zbekiston milliy ensiklopediyasi$$),
((SELECT id FROM heroes WHERE slug = 'amir-temur'), $$Davlat asoslashi$$,
 $$1370-yilda Movarounnahrda markazlashgan davlatga asos soldim. Poytaxt etib Samarqandni tanladim va uni dunyoning eng go'zal shahriga aylantirishga intildim.$$,
 $$["davlat", "1370", "poytaxt", "samarqand", "asos", "markazlashgan"]$$,
 $$«O'zbekiston tarixi» 7-sinf darsligi$$),
((SELECT id FROM heroes WHERE slug = 'amir-temur'), $$Sohibqiron unvoni$$,
 $$Meni Sohibqiron deb ataydilar — bu «baxtli yulduzlar birlashuvi davrida tug'ilgan» degan ma'noni anglatadi va g'alabalarim sharafiga berilgan.$$,
 $$["sohibqiron", "unvon", "laqab", "nima uchun", "nom"]$$,
 $$O'zbekiston milliy ensiklopediyasi$$),
((SELECT id FROM heroes WHERE slug = 'amir-temur'), $$Harbiy yurishlar$$,
 $$Umrim davomida ko'plab harbiy yurishlar qildim: To'xtamishxonga qarshi (1391, 1395), Hindistonga (1398–1399), 1402-yilda esa Anqara jangida Usmonli sultoni Boyazid Yildirimni mag'lub etdim.$$,
 $$["jang", "urush", "yurish", "anqara", "boyazid", "toxtamish", "hindiston", "harbiy", "lashkar", "qoshin"]$$,
 $$«O'zbekiston tarixi» 7-sinf darsligi$$),
((SELECT id FROM heroes WHERE slug = 'amir-temur'), $$«Temur tuzuklari»$$,
 $$«Temur tuzuklari» asarida davlatni boshqarish qoidalarini bayon qilganman. Shiorim: «Kuch — adolatda».$$,
 $$["tuzuk", "kitob", "asar", "shior", "adolat", "kuch", "yozgan", "boshqarish"]$$,
 $$«Temur tuzuklari»$$),
((SELECT id FROM heroes WHERE slug = 'amir-temur'), $$Bunyodkorlik$$,
 $$Davrimda Samarqandda Bibixonim jome masjidi va Go'ri Amir maqbarasi, Shahrisabzda Oqsaroy qad ko'tardi. «Qudratimizga shubha qilsang — binolarimizga boq!» derdim.$$,
 $$["masjid", "bibixonim", "oqsaroy", "gori amir", "qur", "bino", "maqbara", "memor", "inshoot"]$$,
 $$O'zbekiston milliy ensiklopediyasi$$),
((SELECT id FROM heroes WHERE slug = 'amir-temur'), $$Oilasi$$,
 $$Farzandlarim: Jahongir, Umarshayx, Mironshoh va Shohrux. Sevimli nabiralarimdan biri — olim Mirzo Ulug'bek, u Shohruxning o'g'lidir.$$,
 $$["ogil", "farzand", "oila", "shohrux", "nabira", "ulugbek", "jahongir", "avlod"]$$,
 $$O'zbekiston milliy ensiklopediyasi$$),
((SELECT id FROM heroes WHERE slug = 'amir-temur'), $$Elchilik aloqalari$$,
 $$Yevropa davlatlari bilan elchilik aloqalari o'rnatganman: Ispaniya elchisi Rui Gonsales de Klavixo saroyimda mehmon bo'lgan, Fransiya va Angliya qirollari bilan yozishmalar olib borganman.$$,
 $$["elchi", "klavixo", "ispaniya", "yevropa", "fransiya", "angliya", "yozishma"]$$,
 $$Klavixo kundaliklari, O'zbekiston milliy ensiklopediyasi$$),
((SELECT id FROM heroes WHERE slug = 'amir-temur'), $$Ipak yo'li savdosi$$,
 $$Buyuk ipak yo'li savdosini rivojlantirdim: karvon yo'llarini xavfsiz qildim, Samarqandni dunyo savdo markaziga aylantirdim.$$,
 $$["savdo", "ipak", "karvon", "iqtisod"]$$,
 $$«O'zbekiston tarixi» 7-sinf darsligi$$),
((SELECT id FROM heroes WHERE slug = 'amir-temur'), $$Vafoti$$,
 $$1405-yil 18-fevralda Xitoyga yurish boshida O'tror shahrida vafot etganman. Meni Samarqanddagi Go'ri Amir maqbarasiga dafn etishgan.$$,
 $$["vafot", "otror", "dafn", "qabr", "umr oxiri", "xitoy"]$$,
 $$O'zbekiston milliy ensiklopediyasi$$);

-- ============ FAKT KARTOCHKALARI: MIRZO ULUG'BEK ============

INSERT INTO fact_cards (hero_id, topic_uz, fact_uz, keywords, source) VALUES
((SELECT id FROM heroes WHERE slug = 'mirzo-ulugbek'), $$Tug'ilishi$$,
 $$Men 1394-yil 22-martda Sultoniya shahrida, harbiy yurish paytida tug'ilganman. Asl ismim — Muhammad Tarag'ay. Bobom — buyuk Amir Temur, otam — Shohrux Mirzo.$$,
 $$["tugil", "ism", "taragay", "bobo", "ota", "sultoniya", "shohrux"]$$,
 $$O'zbekiston milliy ensiklopediyasi$$),
((SELECT id FROM heroes WHERE slug = 'mirzo-ulugbek'), $$Hukmronligi$$,
 $$1409-yildan Samarqand taxtiga o'tirdim va Movarounnahrni qariyb qirq yil boshqardim. Davrimda Samarqand butun Sharqning ilm-fan markaziga aylandi.$$,
 $$["hukmdor", "taxt", "boshqar", "1409", "podshoh", "hukmronlik", "davlat"]$$,
 $$«O'zbekiston tarixi» 7-sinf darsligi$$),
((SELECT id FROM heroes WHERE slug = 'mirzo-ulugbek'), $$Rasadxona$$,
 $$1424–1429-yillarda Samarqandda ulkan rasadxona qurdirdim. Bosh asbobi — radiusi 40 metrga yaqin ulkan sekstant. U yerda yulduzlarni kuzatib, aniq jadvallar tuzardik.$$,
 $$["rasadxona", "observatoriya", "sekstant", "qur", "asbob"]$$,
 $$O'zbekiston milliy ensiklopediyasi$$),
((SELECT id FROM heroes WHERE slug = 'mirzo-ulugbek'), $$«Ziji jadidi Ko'ragoniy»$$,
 $$«Ziji jadidi Ko'ragoniy» asarimda 1018 yulduzning aniq jadvalini tuzdim. Bu asar asrlar davomida Sharq va Yevropada astronomiya qo'llanmasi bo'lib xizmat qildi.$$,
 $$["zij", "yulduz", "jadval", "asar", "kitob", "astronomiya", "koragoniy"]$$,
 $$O'zbekiston milliy ensiklopediyasi$$),
((SELECT id FROM heroes WHERE slug = 'mirzo-ulugbek'), $$Yil hisobi$$,
 $$Yil uzunligini 365 kun 6 soat 10 daqiqa 8 soniya deb hisoblaganman — bu hozirgi zamon o'lchovidan bir daqiqadan kamroq farq qiladi.$$,
 $$["yil uzunligi", "hisob", "aniqlik", "daqiqa", "olchov"]$$,
 $$«Ziji jadidi Ko'ragoniy»$$),
((SELECT id FROM heroes WHERE slug = 'mirzo-ulugbek'), $$Madrasalari$$,
 $$Uchta madrasa qurdirganman: Buxoroda (1417), Samarqand Registonida (1417–1420) va G'ijduvonda (1433). Buxoro madrasasi darvozasiga «Bilim olish har bir muslim erkak va ayolning burchidir» degan hadis bitilgan.$$,
 $$["madrasa", "registon", "talim", "bilim", "maktab", "buxoro", "gijduvon"]$$,
 $$O'zbekiston milliy ensiklopediyasi$$),
((SELECT id FROM heroes WHERE slug = 'mirzo-ulugbek'), $$Olimlar davrasi$$,
 $$Atrofimga zamonamning eng yetuk olimlarini to'pladim: ustozim Qozizoda Rumiy, G'iyosiddin Jamshid Koshiy va shogirdim Ali Qushchi.$$,
 $$["olim", "qushchi", "koshiy", "rumiy", "shogird", "ustoz", "akademiya"]$$,
 $$O'zbekiston milliy ensiklopediyasi$$),
((SELECT id FROM heroes WHERE slug = 'mirzo-ulugbek'), $$Vafoti$$,
 $$1449-yil 27-oktabrda o'g'lim Abdullatif fitnasi natijasida shahid bo'lganman. Keyinchalik meni Go'ri Amirda bobom yoniga dafn etishgan.$$,
 $$["vafot", "abdullatif", "shahid", "dafn", "qabr", "fitna"]$$,
 $$O'zbekiston milliy ensiklopediyasi$$);

-- ============ FAKT KARTOCHKALARI: ALISHER NAVOIY ============

INSERT INTO fact_cards (hero_id, topic_uz, fact_uz, keywords, source) VALUES
((SELECT id FROM heroes WHERE slug = 'alisher-navoiy'), $$Tug'ilishi$$,
 $$Men 1441-yil 9-fevralda Hirot shahrida tug'ilganman. Asl ismim — Nizomiddin Mir Alisher.$$,
 $$["tugil", "ism", "hirot", "bolalik"]$$,
 $$O'zbekiston milliy ensiklopediyasi$$),
((SELECT id FROM heroes WHERE slug = 'alisher-navoiy'), $$Ona tili himoyasi$$,
 $$Turkiy (eski o'zbek) tilining buyuk himoyachisiman. «Muhokamat ul-lug'atayn» (1499) asarimda turkiy til fors tilidan qolishmasligini isbotlaganman.$$,
 $$["til", "muhokamat", "turkiy", "ozbek", "fors", "lugatayn"]$$,
 $$«Muhokamat ul-lug'atayn»$$),
((SELECT id FROM heroes WHERE slug = 'alisher-navoiy'), $$«Xamsa»$$,
 $$1483–1485-yillarda «Xamsa» yaratdim — besh doston: «Hayrat ul-abror», «Farhod va Shirin», «Layli va Majnun», «Sab'ai sayyor» va «Saddi Iskandariy».$$,
 $$["xamsa", "doston", "farhod", "layli", "majnun", "hayrat", "iskandariy", "sayyor", "besh"]$$,
 $$O'zbekiston milliy ensiklopediyasi$$),
((SELECT id FROM heroes WHERE slug = 'alisher-navoiy'), $$Davlat xizmati$$,
 $$Do'stim Husayn Boyqaro saltanatida avval muhrdor (1469), so'ng vazir (1472) bo'lib xizmat qildim. Adolat va xalq farovonligi uchun kurashdim.$$,
 $$["vazir", "boyqaro", "muhrdor", "xizmat", "dost", "saroy", "husayn"]$$,
 $$O'zbekiston milliy ensiklopediyasi$$),
((SELECT id FROM heroes WHERE slug = 'alisher-navoiy'), $$Xayriya ishlari$$,
 $$Daromadimni xalq uchun sarfladim: 300 ga yaqin inshoot — madrasalar, masjidlar, shifoxonalar, hammomlar, ko'priklar va ariqlar qurdirganman. «Ixlosiya» madrasasi shulardan biri.$$,
 $$["xayriya", "qur", "madrasa", "koprik", "shifoxona", "inshoot", "ixlosiya", "savob"]$$,
 $$O'zbekiston milliy ensiklopediyasi$$),
((SELECT id FROM heroes WHERE slug = 'alisher-navoiy'), $$Devonlari$$,
 $$She'rlarimni «Xazoyin ul-maoniy» nomli to'rt devonga jamlaganman (1491–1498), unda qirq besh mingdan ortiq misra bor.$$,
 $$["devon", "sher", "gazal", "xazoyin", "misra", "maoniy"]$$,
 $$O'zbekiston milliy ensiklopediyasi$$),
((SELECT id FROM heroes WHERE slug = 'alisher-navoiy'), $$Taxallusi$$,
 $$Turkiy she'rlarimda «Navoiy» (navo — kuy degani), forsiy she'rlarimda «Foniy» taxallusini qo'llaganman.$$,
 $$["taxallus", "foniy", "nega navoiy", "kuy", "navo"]$$,
 $$O'zbekiston milliy ensiklopediyasi$$),
((SELECT id FROM heroes WHERE slug = 'alisher-navoiy'), $$«Lison ut-tayr»$$,
 $$Umrim oxirida «Lison ut-tayr» («Qushlar tili», 1499) dostonini yozdim — unda haqiqatni izlagan qushlar qissasi bayon etiladi.$$,
 $$["lison", "qush", "tayr"]$$,
 $$O'zbekiston milliy ensiklopediyasi$$),
((SELECT id FROM heroes WHERE slug = 'alisher-navoiy'), $$Vafoti$$,
 $$1501-yil 3-yanvarda ona shahrim Hirotda vafot etganman. Butun shahar motam tutgan edi.$$,
 $$["vafot", "dafn", "qabr", "motam"]$$,
 $$O'zbekiston milliy ensiklopediyasi$$);

-- ============ TARIXIY VOQEALAR (M3 vaqt lentasi) ============

INSERT INTO historical_events (era_id, title_uz, year_from, year_to, location_uz, description_uz) VALUES
((SELECT id FROM eras WHERE code = 'qadimgi'), $$«Avesto»ning shakllanishi$$, -800, -600, $$Xorazm$$,
 $$Zardushtiylik dinining muqaddas kitobi «Avesto»ning eng qadimgi qismlari shu hududda shakllangan. U xalqimizning qadimgi tarixi haqidagi eng muhim yozma manbalardan biridir.$$),
((SELECT id FROM eras WHERE code = 'qadimgi'), $$Ilk davlatlar: Katta Xorazm, Baqtriya, So'g'diyona$$, -700, -500, $$Movarounnahr$$,
 $$Hududimizda ilk davlat birlashmalari — Katta Xorazm, Baqtriya podsholigi va So'g'diyona vujudga keldi.$$),
((SELECT id FROM eras WHERE code = 'antik'), $$Iskandar Maqduniy yurishi va Spitamen qo'zg'oloni$$, -329, -327, $$So'g'diyona$$,
 $$Iskandar Maqduniy (Aleksandr Makedonskiy) So'g'diyonaga bostirib kirdi. Spitamen boshchiligidagi xalq qo'zg'oloni bosqinchilarga uch yil qattiq qarshilik ko'rsatdi.$$),
((SELECT id FROM eras WHERE code = 'antik'), $$Buyuk ipak yo'lining ochilishi$$, -150, NULL, $$Movarounnahr$$,
 $$Xitoyni O'rta yer dengizi bilan bog'lagan Buyuk ipak yo'li mintaqamiz orqali o'tib, Samarqand va Buxoroni dunyo savdosining markaziga aylantirdi.$$),
((SELECT id FROM eras WHERE code = 'antik'), $$Kushon saltanatining yuksalishi$$, 100, 300, $$Baqtriya$$,
 $$Kushon saltanati o'z davrining eng qudratli davlatlaridan biri edi; savdo, shaharsozlik va madaniyat gullab-yashnadi.$$),
((SELECT id FROM eras WHERE code = 'arab'), $$Qutayba ibn Muslim yurishlari$$, 709, 712, $$Buxoro va Samarqand$$,
 $$Arab lashkarboshisi Qutayba ibn Muslim Buxoro (709) va Samarqandni (712) egalladi. Movarounnahrga islom dini kirib keldi.$$),
((SELECT id FROM eras WHERE code = 'arab'), $$Imom al-Buxoriy faoliyati$$, 810, 870, $$Buxoro$$,
 $$Imom al-Buxoriy — hadis ilmining sultoni. Uning «Al-jomi' as-sahih» to'plami islom olamida Qur'ondan keyingi eng ishonchli manba sanaladi.$$),
((SELECT id FROM eras WHERE code = 'arab'), $$Al-Xorazmiy va algebra fanining tug'ilishi$$, 820, 850, $$Xorazm — Bag'dod$$,
 $$Muhammad ibn Muso al-Xorazmiy algebra faniga asos soldi; «algoritm» so'zi uning nomidan kelib chiqqan.$$),
((SELECT id FROM eras WHERE code = 'temuriylar'), $$Amir Temur davlatining tashkil topishi$$, 1370, NULL, $$Samarqand$$,
 $$Amir Temur Movarounnahrda markazlashgan davlatga asos soldi va Samarqandni poytaxt qildi.$$),
((SELECT id FROM eras WHERE code = 'temuriylar'), $$Anqara jangi$$, 1402, NULL, $$Anqara$$,
 $$Amir Temur Usmonli sultoni Boyazid Yildirimni mag'lub etdi — bu jahon tarixidagi eng yirik janglardan biri edi.$$),
((SELECT id FROM eras WHERE code = 'temuriylar'), $$Ulug'bek rasadxonasining qurilishi$$, 1424, 1429, $$Samarqand$$,
 $$Mirzo Ulug'bek dunyodagi eng ilg'or rasadxonani qurdirdi; unda 1018 yulduzning aniq jadvali tuzildi.$$),
((SELECT id FROM eras WHERE code = 'temuriylar'), $$Navoiy «Xamsa»ni yaratdi$$, 1483, 1485, $$Hirot$$,
 $$Alisher Navoiy turkiy tilda birinchi to'liq «Xamsa» — besh dostonni yaratib, ona tilimiz qudratini butun dunyoga ko'rsatdi.$$),
((SELECT id FROM eras WHERE code = 'xonliklar'), $$Shayboniylar Movarounnahrni egallashi$$, 1500, 1506, $$Samarqand va Buxoro$$,
 $$Muhammad Shayboniyxon boshchiligidagi ko'chmanchi o'zbeklar temuriylar davlatini egallab, shayboniylar sulolasiga asos soldi.$$),
((SELECT id FROM eras WHERE code = 'xonliklar'), $$Xiva xonligining tashkil topishi$$, 1512, NULL, $$Xorazm$$,
 $$Xorazm hududida mustaqil Xiva xonligi vujudga keldi.$$),
((SELECT id FROM eras WHERE code = 'xonliklar'), $$Qo'qon xonligining tashkil topishi$$, 1709, NULL, $$Farg'ona vodiysi$$,
 $$Farg'ona vodiysida Qo'qon xonligi tashkil topdi. Shu tariqa uch davlat — Buxoro, Xiva va Qo'qon shakllandi.$$),
((SELECT id FROM eras WHERE code = 'jadidlar'), $$Rossiya imperiyasining Toshkentni bosib olishi$$, 1865, NULL, $$Toshkent$$,
 $$Rossiya imperiyasi qo'shinlari Toshkentni bosib oldi — Turkiston mustamlakaga aylandi.$$),
((SELECT id FROM eras WHERE code = 'jadidlar'), $$Yangi usul (jadid) maktablarining ochilishi$$, 1893, 1910, $$Turkiston$$,
 $$Ma'rifatparvar jadidlar zamonaviy bilim beruvchi yangi usul maktablarini ochdilar: ular millatni ilm orqali uyg'otishni maqsad qildilar.$$),
((SELECT id FROM eras WHERE code = 'jadidlar'), $$Behbudiyning «Padarkush» dramasi$$, 1913, NULL, $$Samarqand$$,
 $$Mahmudxo'ja Behbudiy birinchi o'zbek dramasi — «Padarkush»ni yozdi. U jaholat fojiasini sahnada ko'rsatib, xalqni ilmga chorladi.$$),
((SELECT id FROM eras WHERE code = 'xx-asr'), $$Turkiston muxtoriyati$$, 1917, 1918, $$Qo'qon$$,
 $$Qo'qonda Turkiston muxtoriyati e'lon qilindi — o'lkadagi ilk demokratik davlatchilik tajribasi. U 72 kundan so'ng bolsheviklar tomonidan tugatildi.$$),
((SELECT id FROM eras WHERE code = 'xx-asr'), $$O'zbekiston SSR tashkil etilishi$$, 1924, NULL, $$Toshkent$$,
 $$Milliy-hududiy chegaralanish natijasida O'zbekiston SSR tashkil etildi.$$),
((SELECT id FROM eras WHERE code = 'xx-asr'), $$Toshkent zilzilasi$$, 1966, NULL, $$Toshkent$$,
 $$Kuchli zilzila Toshkent markazini vayron qildi; shahar qisqa muddatda qayta qurildi va yangi qiyofa oldi.$$),
((SELECT id FROM eras WHERE code = 'mustaqillik'), $$Mustaqillik e'lon qilinishi$$, 1991, NULL, $$Toshkent$$,
 $$1991-yil 31-avgustda O'zbekiston Respublikasining davlat mustaqilligi e'lon qilindi. 1-sentabr — Mustaqillik kuni.$$),
((SELECT id FROM eras WHERE code = 'mustaqillik'), $$Konstitutsiya qabul qilinishi$$, 1992, NULL, $$Toshkent$$,
 $$1992-yil 8-dekabrda O'zbekiston Respublikasining Konstitutsiyasi qabul qilindi.$$),
((SELECT id FROM eras WHERE code = 'mustaqillik'), $$Milliy valyuta — so'm muomalaga kiritilishi$$, 1994, NULL, $$O'zbekiston$$,
 $$1994-yil 1-iyuldan milliy valyuta — so'm muomalaga kiritildi.$$);

-- ============ SAVOLLAR BANKI: QAHRAMONLAR (M1 mikro-viktorina) ============

INSERT INTO quiz_questions (hero_id, era_id, question_uz, options, correct_index, explanation_uz) VALUES
((SELECT id FROM heroes WHERE slug = 'amir-temur'), NULL,
 $$Amir Temur qachon tug'ilgan?$$,
 $$["1370-yil", "1336-yil", "1405-yil", "1341-yil"]$$, 1,
 $$Amir Temur 1336-yil 9-aprelda Shahrisabz yaqinidagi Xo'ja Ilg'or qishlog'ida tug'ilgan.$$),
((SELECT id FROM heroes WHERE slug = 'amir-temur'), NULL,
 $$Amir Temur davlatining poytaxti qaysi shahar edi?$$,
 $$["Buxoro", "Hirot", "Samarqand", "Toshkent"]$$, 2,
 $$1370-yilda davlatga asos solgan Amir Temur poytaxt etib Samarqandni tanlagan.$$),
((SELECT id FROM heroes WHERE slug = 'amir-temur'), NULL,
 $$1402-yilgi Anqara jangida Amir Temur kimni mag'lub etgan?$$,
 $$["Boyazid Yildirim", "To'xtamishxon", "Chingizxon", "Sulton Mahmud"]$$, 0,
 $$Anqara jangida Usmonli sultoni Boyazid Yildirim mag'lub etilgan.$$),
((SELECT id FROM heroes WHERE slug = 'amir-temur'), NULL,
 $$Davlat boshqaruvi qoidalari bayon etilgan Amir Temur asari qanday nomlanadi?$$,
 $$["«Boburnoma»", "«Xamsa»", "«Zafarnoma»", "«Temur tuzuklari»"]$$, 3,
 $$«Temur tuzuklari»da davlatni boshqarish qoidalari bayon etilgan.$$),
((SELECT id FROM heroes WHERE slug = 'amir-temur'), NULL,
 $$Amir Temurning mashhur shiori qaysi?$$,
 $$["«Kuch — adolatda»", "«Bilim — kuch»", "«Birlik — baxt»", "«Vatan — muqaddas»"]$$, 0,
 $$Amir Temurning shiori — «Kuch — adolatda».$$),
((SELECT id FROM heroes WHERE slug = 'mirzo-ulugbek'), NULL,
 $$Ulug'bek rasadxonasi qachon qurilgan?$$,
 $$["1409–1411-yillarda", "1424–1429-yillarda", "1370–1375-yillarda", "1449–1452-yillarda"]$$, 1,
 $$Rasadxona 1424–1429-yillarda Samarqandda qurilgan.$$),
((SELECT id FROM heroes WHERE slug = 'mirzo-ulugbek'), NULL,
 $$«Ziji jadidi Ko'ragoniy»da nechta yulduz jadvali berilgan?$$,
 $$["515", "2500", "1018", "100"]$$, 2,
 $$Ulug'bek ziji 1018 yulduzning aniq jadvalini o'z ichiga oladi.$$),
((SELECT id FROM heroes WHERE slug = 'mirzo-ulugbek'), NULL,
 $$Mirzo Ulug'bek kimning nabirasi?$$,
 $$["Amir Temur", "Bobur", "Shayboniyxon", "Husayn Boyqaro"]$$, 0,
 $$Ulug'bek — Amir Temurning nabirasi, Shohrux Mirzoning o'g'li.$$),
((SELECT id FROM heroes WHERE slug = 'mirzo-ulugbek'), NULL,
 $$Ulug'bekning asl ismi nima?$$,
 $$["Nizomiddin Mir Alisher", "Muhammad Tarag'ay", "Zahiriddin Muhammad", "Shohrux Mirzo"]$$, 1,
 $$Ulug'bekning asl ismi — Muhammad Tarag'ay.$$),
((SELECT id FROM heroes WHERE slug = 'mirzo-ulugbek'), NULL,
 $$Ulug'bek qaysi fan rivojiga eng katta hissa qo'shgan?$$,
 $$["Kimyo", "Biologiya", "Geografiya", "Astronomiya"]$$, 3,
 $$Ulug'bek buyuk astronom bo'lgan: rasadxona qurdirgan va yulduzlar jadvalini tuzgan.$$),
((SELECT id FROM heroes WHERE slug = 'alisher-navoiy'), NULL,
 $$Navoiyning «Xamsa»si nechta dostondan iborat?$$,
 $$["To'rtta", "Beshta", "Yettita", "Uchta"]$$, 1,
 $$«Xamsa» so'zi «beshlik» degani — u besh dostondan iborat.$$),
((SELECT id FROM heroes WHERE slug = 'alisher-navoiy'), NULL,
 $$«Xamsa»ning birinchi dostoni qaysi?$$,
 $$["«Farhod va Shirin»", "«Layli va Majnun»", "«Hayrat ul-abror»", "«Saddi Iskandariy»"]$$, 2,
 $$«Xamsa» «Hayrat ul-abror» dostoni bilan boshlanadi.$$),
((SELECT id FROM heroes WHERE slug = 'alisher-navoiy'), NULL,
 $$«Muhokamat ul-lug'atayn» asarida Navoiy nimani isbotlagan?$$,
 $$["Turkiy til fors tilidan qolishmasligini", "She'r yozish qoidalarini", "Tarix ilmining foydasini", "Savdo yo'llarining ahamiyatini"]$$, 0,
 $$Navoiy bu asarda turkiy tilning boyligi va qudratini isbotlagan.$$),
((SELECT id FROM heroes WHERE slug = 'alisher-navoiy'), NULL,
 $$Alisher Navoiy qayerda tug'ilgan?$$,
 $$["Samarqand", "Buxoro", "Toshkent", "Hirot"]$$, 3,
 $$Navoiy 1441-yilda Hirot shahrida tug'ilgan.$$),
((SELECT id FROM heroes WHERE slug = 'alisher-navoiy'), NULL,
 $$Navoiy forsiy she'rlarida qaysi taxallusni qo'llagan?$$,
 $$["Foniy", "Navoiy", "Bobur", "Mashrab"]$$, 0,
 $$Forsiy she'rlarida «Foniy», turkiy she'rlarida «Navoiy» taxallusini qo'llagan.$$);

-- ============ SAVOLLAR BANKI: DAVRLAR (M4 testlar) ============

INSERT INTO quiz_questions (hero_id, era_id, question_uz, options, correct_index, explanation_uz) VALUES
(NULL, (SELECT id FROM eras WHERE code = 'qadimgi'),
 $$«Avesto» qaysi dinning muqaddas kitobi?$$,
 $$["Buddaviylik", "Zardushtiylik", "Islom", "Xristianlik"]$$, 1,
 $$«Avesto» — zardushtiylik dinining muqaddas kitobi, eng qadimgi qismlari Xorazmda shakllangan.$$),
(NULL, (SELECT id FROM eras WHERE code = 'qadimgi'),
 $$Hududimizdagi eng qadimgi davlatlar qaysilar?$$,
 $$["Rim va Afina", "Misr va Bobil", "Baqtriya, Xorazm, So'g'diyona", "Xitoy va Hindiston"]$$, 2,
 $$Ilk davlatlarimiz — Katta Xorazm, Baqtriya va So'g'diyona.$$),
(NULL, (SELECT id FROM eras WHERE code = 'antik'),
 $$Iskandar Maqduniy Movarounnahrga qachon bostirib kirgan?$$,
 $$["Miloddan avvalgi 329-yil", "Miloddan avvalgi 500-yil", "Milodiy 100-yil", "Miloddan avvalgi 100-yil"]$$, 0,
 $$Iskandar mil. avv. 329-yilda So'g'diyonaga bostirib kirgan.$$),
(NULL, (SELECT id FROM eras WHERE code = 'antik'),
 $$Iskandarga qarshi xalq qo'zg'oloniga kim boshchilik qilgan?$$,
 $$["To'maris", "Shiroq", "Muqanna", "Spitamen"]$$, 3,
 $$Spitamen boshchiligidagi qo'zg'olon bosqinchilarga uch yil qarshilik ko'rsatgan.$$),
(NULL, (SELECT id FROM eras WHERE code = 'arab'),
 $$«Algoritm» so'zi qaysi olim nomidan kelib chiqqan?$$,
 $$["Ibn Sino", "Al-Xorazmiy", "Beruniy", "Al-Farg'oniy"]$$, 1,
 $$«Algoritm» — Muhammad al-Xorazmiy nomining lotincha talaffuzidan kelib chiqqan.$$),
(NULL, (SELECT id FROM eras WHERE code = 'arab'),
 $$Hadis ilmining sultoni deb tan olingan vatandoshimiz kim?$$,
 $$["Imom al-Buxoriy", "At-Termiziy", "Az-Zamaxshariy", "Al-Marg'inoniy"]$$, 0,
 $$Imom al-Buxoriyning «Al-jomi' as-sahih» to'plami eng ishonchli hadislar manbasi sanaladi.$$),
(NULL, (SELECT id FROM eras WHERE code = 'temuriylar'),
 $$Amir Temur markazlashgan davlatga qachon asos solgan?$$,
 $$["1336-yil", "1405-yil", "1370-yil", "1449-yil"]$$, 2,
 $$1370-yilda Movarounnahrda markazlashgan davlat tashkil topgan.$$),
(NULL, (SELECT id FROM eras WHERE code = 'temuriylar'),
 $$Samarqand Registonidagi Ulug'bek madrasasi qachon qurilgan?$$,
 $$["1417–1420-yillarda", "1370–1372-yillarda", "1500–1506-yillarda", "1483–1485-yillarda"]$$, 0,
 $$Registondagi Ulug'bek madrasasi 1417–1420-yillarda qurilgan.$$),
(NULL, (SELECT id FROM eras WHERE code = 'xonliklar'),
 $$Movarounnahrni 1500–1506-yillarda kim egallagan?$$,
 $$["Bobur", "Muhammad Shayboniyxon", "Husayn Boyqaro", "Nodirshoh"]$$, 1,
 $$Muhammad Shayboniyxon temuriylar davlatini egallab, yangi sulolaga asos solgan.$$),
(NULL, (SELECT id FROM eras WHERE code = 'xonliklar'),
 $$XVIII–XIX asrlarda hududimizda qaysi uch davlat mavjud edi?$$,
 $$["Buxoro, Xiva, Qo'qon", "Samarqand, Toshkent, Farg'ona", "Xorazm, Baqtriya, So'g'd", "Turkiston, Yettisuv, Orol"]$$, 0,
 $$Uch davlat: Buxoro amirligi, Xiva xonligi va Qo'qon xonligi.$$),
(NULL, (SELECT id FROM eras WHERE code = 'jadidlar'),
 $$«Padarkush» dramasining muallifi kim?$$,
 $$["Cho'lpon", "Fitrat", "Mahmudxo'ja Behbudiy", "Munavvarqori"]$$, 2,
 $$Birinchi o'zbek dramasi «Padarkush»ni (1913) Mahmudxo'ja Behbudiy yozgan.$$),
(NULL, (SELECT id FROM eras WHERE code = 'jadidlar'),
 $$Toshkent Rossiya imperiyasi tomonidan qachon bosib olingan?$$,
 $$["1865-yil", "1873-yil", "1876-yil", "1917-yil"]$$, 0,
 $$Toshkent 1865-yilda bosib olinib, Turkiston mustamlakaga aylantirilgan.$$),
(NULL, (SELECT id FROM eras WHERE code = 'xx-asr'),
 $$Turkiston muxtoriyati qaysi shaharda e'lon qilingan?$$,
 $$["Toshkent", "Qo'qon", "Samarqand", "Buxoro"]$$, 1,
 $$Turkiston muxtoriyati 1917-yilda Qo'qonda e'lon qilingan.$$),
(NULL, (SELECT id FROM eras WHERE code = 'xx-asr'),
 $$Toshkent zilzilasi qachon yuz bergan?$$,
 $$["1948-yil", "1975-yil", "1927-yil", "1966-yil"]$$, 3,
 $$1966-yilgi zilziladan so'ng Toshkent qisqa muddatda qayta qurilgan.$$),
(NULL, (SELECT id FROM eras WHERE code = 'mustaqillik'),
 $$O'zbekiston mustaqilligi qachon e'lon qilingan?$$,
 $$["1991-yil 31-avgust", "1990-yil 20-iyun", "1992-yil 8-dekabr", "1991-yil 1-yanvar"]$$, 0,
 $$Mustaqillik 1991-yil 31-avgustda e'lon qilingan; 1-sentabr — Mustaqillik kuni.$$),
(NULL, (SELECT id FROM eras WHERE code = 'mustaqillik'),
 $$O'zbekiston Konstitutsiyasi qachon qabul qilingan?$$,
 $$["1991-yil 31-avgust", "1992-yil 8-dekabr", "1993-yil 1-yanvar", "1994-yil 1-iyul"]$$, 1,
 $$Konstitutsiya 1992-yil 8-dekabrda qabul qilingan.$$);
