-- Tirik tarix: davr testlari bankini kengaytirish — har bir davrda 10 tadan savol.
-- Barcha faktlar maktab dasturi va manbalarga tayanadi, metodist tekshiruvi shart.

-- ============ QADIMGI DAVR (+8) ============

INSERT INTO quiz_questions (hero_id, era_id, question_uz, options, correct_index, explanation_uz) VALUES
(NULL, (SELECT id FROM eras WHERE code = 'qadimgi'),
 $$Zardushtiylik dinining payg'ambari kim?$$,
 $$["Muso", "Zardusht", "Budda", "Konfutsiy"]$$, 1,
 $$Zardusht — zardushtiylik dinining asoschisi; «Avesto» shu dinning muqaddas kitobi.$$),
(NULL, (SELECT id FROM eras WHERE code = 'qadimgi'),
 $$Teshiktosh g'oridan nima topilgan?$$,
 $$["Neandertal bolasi qoldiqlari", "Oltin buyumlar", "Qadimgi qo'lyozma", "Sopol idishlar xazinasi"]$$, 0,
 $$Surxondaryodagi Teshiktosh g'oridan neandertal bolasining qoldiqlari topilgan — bu jahonshumul kashfiyot edi.$$),
(NULL, (SELECT id FROM eras WHERE code = 'qadimgi'),
 $$Qadimgi Baqtriya davlati qaysi daryoning yuqori oqimida joylashgan?$$,
 $$["Sirdaryo", "Volga", "Amudaryo", "Zarafshon"]$$, 2,
 $$Baqtriya — Amudaryoning yuqori oqimidagi qadimgi davlat (hozirgi Surxondaryo va unga qo'shni hududlar).$$),
(NULL, (SELECT id FROM eras WHERE code = 'qadimgi'),
 $$To'maris qaysi xalqning malikasi bo'lgan?$$,
 $$["Massagetlar", "Yunonlar", "Forslar", "Xitoyliklar"]$$, 0,
 $$To'maris — massagetlar malikasi; u fors shohi Kir II qo'shinini mag'lub etgan.$$),
(NULL, (SELECT id FROM eras WHERE code = 'qadimgi'),
 $$Cho'pon Shiroq jasorati kimning qo'shiniga qarshi qaratilgan edi?$$,
 $$["Iskandar qo'shiniga", "Doro I qo'shiniga", "Arab qo'shiniga", "Xitoy qo'shiniga"]$$, 1,
 $$Shiroq fors shohi Doro I qo'shinini ataylab suvsiz sahroga boshlab borib halok qilgan.$$),
(NULL, (SELECT id FROM eras WHERE code = 'qadimgi'),
 $$To'marisga qarshi yurish qilgan fors shohi kim?$$,
 $$["Kserks", "Doro I", "Iskandar", "Kir II"]$$, 3,
 $$Fors shohi Kir II massagetlar yurtiga bostirib kirgan va To'maris boshchiligidagi jangda halok bo'lgan.$$),
(NULL, (SELECT id FROM eras WHERE code = 'qadimgi'),
 $$Bronza davriga oid Sopollitepa yodgorligi qaysi viloyat hududida joylashgan?$$,
 $$["Xorazm", "Farg'ona", "Surxondaryo", "Toshkent"]$$, 2,
 $$Sopollitepa — Surxondaryodagi bronza davri dehqonchilik manzilgohi.$$),
(NULL, (SELECT id FROM eras WHERE code = 'qadimgi'),
 $$«Avesto» kitobi ko'proq qaysi hudud bilan bog'liq deb hisoblanadi?$$,
 $$["Xorazm", "Misr", "Hindiston", "Yunoniston"]$$, 0,
 $$Ko'plab olimlar «Avesto»ning eng qadimgi qismlari Xorazm vohasida yaratilgan deb hisoblaydi.$$);

-- ============ ANTIK DAVR (+8) ============

INSERT INTO quiz_questions (hero_id, era_id, question_uz, options, correct_index, explanation_uz) VALUES
(NULL, (SELECT id FROM eras WHERE code = 'antik'),
 $$Kushon saltanatining eng mashhur hukmdori kim?$$,
 $$["Kanishka", "Kir II", "Doro I", "Iskandar"]$$, 0,
 $$Kanishka davrida Kushon saltanati eng yuksak taraqqiyotga erishgan.$$),
(NULL, (SELECT id FROM eras WHERE code = 'antik'),
 $$Buyuk ipak yo'li qaysi mamlakatlarni bog'lagan?$$,
 $$["Hindistonni Afrika bilan", "Xitoyni O'rta yer dengizi mamlakatlari bilan", "Yunonistonni Misr bilan", "Rossiyani Eron bilan"]$$, 1,
 $$Buyuk ipak yo'li Xitoydan boshlanib, Markaziy Osiyo orqali O'rta yer dengizi mamlakatlarigacha cho'zilgan.$$),
(NULL, (SELECT id FROM eras WHERE code = 'antik'),
 $$Sirdaryo bo'ylarida tashkil topgan qadimgi davlat qaysi?$$,
 $$["Kushon", "Baqtriya", "Qang' davlati", "Parfiya"]$$, 2,
 $$Qang' (Kanguy) davlati Sirdaryoning o'rta oqimida tashkil topgan qudratli davlat edi.$$),
(NULL, (SELECT id FROM eras WHERE code = 'antik'),
 $$Kushonlar davrida Termiz atrofida qaysi din keng tarqalgan?$$,
 $$["Islom", "Xristianlik", "Iudaizm", "Buddizm"]$$, 3,
 $$Kushonlar davrida buddizm keng tarqalgan — Termiz yaqinidagi Fayoztepa va Qoratepa ibodatxonalari bunga guvoh.$$),
(NULL, (SELECT id FROM eras WHERE code = 'antik'),
 $$Afrosiyob — qaysi shaharning qadimgi xarobasi?$$,
 $$["Samarqand", "Buxoro", "Xiva", "Termiz"]$$, 0,
 $$Afrosiyob — qadimgi Samarqandning o'rni; u yerdan mashhur devoriy suratlar topilgan.$$),
(NULL, (SELECT id FROM eras WHERE code = 'antik'),
 $$Buyuk ipak yo'lida tashilgan eng qimmatbaho mahsulot nima edi?$$,
 $$["Tuz", "Ipak", "Temir", "Bug'doy"]$$, 1,
 $$Yo'l nomi ham shundan: Xitoy ipagi eng qimmat va sirli mahsulot sanalgan.$$),
(NULL, (SELECT id FROM eras WHERE code = 'antik'),
 $$Yunon-Baqtriya davlati qachon tashkil topgan?$$,
 $$["Milodiy V asrda", "Mil. avv. I asrda", "Mil. avv. III asr o'rtalarida", "Milodiy X asrda"]$$, 2,
 $$Yunon-Baqtriya davlati mil. avv. III asr o'rtalarida (taxminan 250-yil) salavkiylardan ajralib chiqqan.$$),
(NULL, (SELECT id FROM eras WHERE code = 'antik'),
 $$Ipak yo'li savdosida qaysi xalq savdogarlari yetakchi bo'lgan?$$,
 $$["Misrliklar", "Rimliklar", "Yunonlar", "So'g'dlar"]$$, 3,
 $$So'g'd savdogarlari Ipak yo'lidagi asosiy vositachilar edi; so'g'd tili yo'lning savdo tiliga aylangan.$$);

-- ============ ARABLAR DAVRI (+8) ============

INSERT INTO quiz_questions (hero_id, era_id, question_uz, options, correct_index, explanation_uz) VALUES
(NULL, (SELECT id FROM eras WHERE code = 'arab'),
 $$«Movarounnahr» so'zi qanday ma'noni anglatadi?$$,
 $$["Daryoning narigi tomoni", "Buyuk sahro", "Tog'lar yurti", "Quyosh mamlakati"]$$, 0,
 $$Arabcha «Movarounnahr» — «daryoning narigi tomoni», ya'ni Amudaryodan shimoldagi hududlar.$$),
(NULL, (SELECT id FROM eras WHERE code = 'arab'),
 $$Movarounnahrni bosib olishga boshchilik qilgan arab sarkardasi kim?$$,
 $$["Xolid ibn Valid", "Qutayba ibn Muslim", "Amr ibn Os", "Muso ibn Nusayr"]$$, 1,
 $$Qutayba ibn Muslim 709–712-yillarda Buxoro, Samarqand va Xorazmni bosib olgan.$$),
(NULL, (SELECT id FROM eras WHERE code = 'arab'),
 $$Ahmad al-Farg'oniy qaysi fan bo'yicha mashhur olim?$$,
 $$["Tibbiyot", "She'riyat", "Astronomiya", "Musiqa"]$$, 2,
 $$Al-Farg'oniy — buyuk astronom; uning «Astronomiya asoslari» kitobi Yevropada asrlar davomida darslik bo'lgan.$$),
(NULL, (SELECT id FROM eras WHERE code = 'arab'),
 $$Ibn Sinoning mashhur tibbiy asari qaysi?$$,
 $$["«Boburnoma»", "«Xamsa»", "«Al-jabr»", "«Tib qonunlari»"]$$, 3,
 $$Ibn Sinoning «Tib qonunlari» asari 600 yil davomida Yevropa universitetlarida darslik bo'lgan.$$),
(NULL, (SELECT id FROM eras WHERE code = 'arab'),
 $$Muqanna qo'zg'oloni kimlarga qarshi ko'tarilgan?$$,
 $$["Arab xalifaligiga", "Mo'g'ullarga", "Forslarga", "Yunonlarga"]$$, 0,
 $$Muqanna boshchiligidagi «oq kiyimlilar» qo'zg'oloni (VIII asr) arab xalifaligi hukmronligiga qarshi edi.$$),
(NULL, (SELECT id FROM eras WHERE code = 'arab'),
 $$Somoniylar davlatining poytaxti qaysi shahar edi?$$,
 $$["Samarqand", "Buxoro", "Marv", "Urganch"]$$, 1,
 $$IX–X asrlarda Somoniylar davlatining poytaxti Buxoro bo'lib, yirik ilm-fan markaziga aylangan.$$),
(NULL, (SELECT id FROM eras WHERE code = 'arab'),
 $$Imom at-Termiziy qaysi ilm sohasining buyuk olimi?$$,
 $$["Matematika", "Geografiya", "Hadis ilmi", "Kimyo"]$$, 2,
 $$Imom at-Termiziy — «Sunani Termiziy» to'plamini tuzgan buyuk muhaddis.$$),
(NULL, (SELECT id FROM eras WHERE code = 'arab'),
 $$Abu Nasr Forobiy qanday nom bilan ulug'langan?$$,
 $$["«Shayx ur-rais»", "«Sohibqiron»", "«Hadis sultoni»", "«Ikkinchi muallim»"]$$, 3,
 $$Forobiy Arastudan (Aristotel) keyingi eng buyuk faylasuf sifatida «Ikkinchi muallim» deb atalgan.$$);

-- ============ TEMURIYLAR DAVRI (+8) ============

INSERT INTO quiz_questions (hero_id, era_id, question_uz, options, correct_index, explanation_uz) VALUES
(NULL, (SELECT id FROM eras WHERE code = 'temuriylar'),
 $$Ulug'bek rasadxonasi qachon qurilgan?$$,
 $$["1428–1429-yillarda", "1370-yilda", "1501-yilda", "1526-yilda"]$$, 0,
 $$Mirzo Ulug'bek Samarqandda 1428–1429-yillarda uch qavatli ulkan rasadxona qurdirgan.$$),
(NULL, (SELECT id FROM eras WHERE code = 'temuriylar'),
 $$«Xamsa» — besh dostondan iborat asar muallifi kim?$$,
 $$["Bobur", "Alisher Navoiy", "Ulug'bek", "Jomiy"]$$, 1,
 $$Alisher Navoiy 1483–1485-yillarda turkiy tilda «Xamsa» — besh dostonni yaratgan.$$),
(NULL, (SELECT id FROM eras WHERE code = 'temuriylar'),
 $$Nima uchun temuriylar davri «Sharq Uyg'onish davri» deb ataladi?$$,
 $$["Urushlar ko'p bo'lgani uchun", "Savdo to'xtagani uchun", "Ilm-fan va madaniyat gullab-yashnagani uchun", "Poytaxt ko'chirilgani uchun"]$$, 2,
 $$Bu davrda astronomiya, adabiyot, me'morlik va san'at misli ko'rilmagan darajada rivojlangan.$$),
(NULL, (SELECT id FROM eras WHERE code = 'temuriylar'),
 $$Amir Temur maqbarasi — Go'ri Amir qaysi shaharda joylashgan?$$,
 $$["Toshkent", "Shahrisabz", "Buxoro", "Samarqand"]$$, 3,
 $$Go'ri Amir maqbarasi Samarqandda bo'lib, unda Amir Temur va temuriylar dafn etilgan.$$),
(NULL, (SELECT id FROM eras WHERE code = 'temuriylar'),
 $$Ulug'bekning «Ziji jadidi Ko'ragoniy» asari nimaga bag'ishlangan?$$,
 $$["Yulduzlar jadvaliga", "She'riyatga", "Tibbiyotga", "Tarixga"]$$, 0,
 $$«Zij» — Ulug'bek rasadxonasida tuzilgan 1018 yulduzning aniq jadvali.$$),
(NULL, (SELECT id FROM eras WHERE code = 'temuriylar'),
 $$Husayn Boyqaro davrida madaniyat markazi bo'lgan shahar qaysi?$$,
 $$["Qo'qon", "Hirot", "Xiva", "Kesh"]$$, 1,
 $$XV asr oxirida Hirot — Navoiy va Behzod ijod qilgan yirik madaniyat markazi edi.$$),
(NULL, (SELECT id FROM eras WHERE code = 'temuriylar'),
 $$Temuriylar davrining mashhur miniatyura rassomi kim?$$,
 $$["Ogahiy", "Mashrab", "Kamoliddin Behzod", "Munis"]$$, 2,
 $$Kamoliddin Behzod — «Sharq Rafaeli» deb atalgan buyuk miniatyura ustasi.$$),
(NULL, (SELECT id FROM eras WHERE code = 'temuriylar'),
 $$«Boburnoma» asarining muallifi kim?$$,
 $$["Alisher Navoiy", "Ulug'bek", "Husayn Boyqaro", "Zahiriddin Muhammad Bobur"]$$, 3,
 $$Bobur o'z hayoti va davri haqida ona tilida «Boburnoma» memuar asarini yozgan.$$);

-- ============ XONLIKLAR DAVRI (+8) ============

INSERT INTO quiz_questions (hero_id, era_id, question_uz, options, correct_index, explanation_uz) VALUES
(NULL, (SELECT id FROM eras WHERE code = 'xonliklar'),
 $$«Shajarayi turk» asarini yozgan Xiva xoni kim?$$,
 $$["Abulg'oziy Bahodirxon", "Muhammad Rahimxon", "Sherg'ozixon", "Eltuzarxon"]$$, 0,
 $$Abulg'oziy Bahodirxon — xon va tarixchi olim, «Shajarayi turk» asarining muallifi.$$),
(NULL, (SELECT id FROM eras WHERE code = 'xonliklar'),
 $$Qo'qon xonligi qaysi vodiyda joylashgan edi?$$,
 $$["Zarafshon vodiysida", "Farg'ona vodiysida", "Surxon vodiysida", "Chirchiq vodiysida"]$$, 1,
 $$Qo'qon xonligining markazi Farg'ona vodiysi edi; keyinchalik Toshkent va boshqa hududlarni ham qamragan.$$),
(NULL, (SELECT id FROM eras WHERE code = 'xonliklar'),
 $$Buxorodagi eng baland qadimiy minora qaysi?$$,
 $$["Islomxo'ja minorasi", "Burana minorasi", "Kalon minorasi", "Qutb minorasi"]$$, 2,
 $$XII asrda qurilgan Kalon minorasi — Buxoroning ramzi, balandligi qariyb 47 metr.$$),
(NULL, (SELECT id FROM eras WHERE code = 'xonliklar'),
 $$Shayboniylardan keyin Buxoro xonligida qaysi sulola hukmronlik qilgan?$$,
 $$["Boburiylar", "Somoniylar", "Qoraxoniylar", "Ashtarxoniylar"]$$, 3,
 $$1601-yildan Buxoro taxtiga Ashtarxoniylar (Joniylar) sulolasi o'tirgan.$$),
(NULL, (SELECT id FROM eras WHERE code = 'xonliklar'),
 $$«Devonai Mashrab» nomi bilan mashhur shoir kim?$$,
 $$["Boborahim Mashrab", "Nodira", "Ogahiy", "Furqat"]$$, 0,
 $$Boborahim Mashrab (XVII asr) — erksevar ruhdagi she'rlari bilan xalq orasida mashhur so'fiy shoir.$$),
(NULL, (SELECT id FROM eras WHERE code = 'xonliklar'),
 $$Qo'qon xonligidagi mashhur shoira, Amiriyning rafiqasi kim?$$,
 $$["Zebunniso", "Nodira", "Uvaysiy", "Anbar otin"]$$, 1,
 $$Nodira — Qo'qon xoni Umarxon (Amiriy)ning rafiqasi, o'zbek mumtoz adabiyotining yirik shoirasi.$$),
(NULL, (SELECT id FROM eras WHERE code = 'xonliklar'),
 $$Xorazmlik shoir, tarjimon va tarixchi — «Riyoz ud-davla» muallifi kim?$$,
 $$["Bedil", "Navoiy", "Ogahiy", "Mashrab"]$$, 2,
 $$Muhammad Rizo Ogahiy — Xiva xonligining shoiri, tarixchisi va mohir tarjimoni.$$),
(NULL, (SELECT id FROM eras WHERE code = 'xonliklar'),
 $$XVI asr boshida Movarounnahrda hokimiyatni qaysi sulola egallagan?$$,
 $$["Temuriylar", "Saljuqiylar", "Qoraxoniylar", "Shayboniylar"]$$, 3,
 $$Muhammad Shayboniyxon boshchiligidagi shayboniylar 1500–1506-yillarda temuriylar davlatini egallagan.$$);

-- ============ JADIDLAR DAVRI (+8) ============

INSERT INTO quiz_questions (hero_id, era_id, question_uz, options, correct_index, explanation_uz) VALUES
(NULL, (SELECT id FROM eras WHERE code = 'jadidlar'),
 $$«Jadid» so'zi qanday ma'noni anglatadi?$$,
 $$["Yangi", "Qadimgi", "Dono", "Botir"]$$, 0,
 $$Arabcha «jadid» — «yangi»; jadidlar ta'lim va jamiyatni yangilash tarafdorlari edi.$$),
(NULL, (SELECT id FROM eras WHERE code = 'jadidlar'),
 $$Jadidlar ochgan maktablar qanday nomlangan?$$,
 $$["Madrasa", "Yangi usul (usuli jadid) maktablari", "Gimnaziya", "Litsey"]$$, 1,
 $$Yangi usul maktablarida bolalar tez savod chiqarib, dunyoviy fanlarni ham o'rgangan.$$),
(NULL, (SELECT id FROM eras WHERE code = 'jadidlar'),
 $$Mahmudxo'ja Behbudiy qaysi shaharda faoliyat yuritgan?$$,
 $$["Toshkentda", "Qo'qonda", "Samarqandda", "Xivada"]$$, 2,
 $$Behbudiy — samarqandlik jadidlar yetakchisi, «Padarkush» dramasi va «Oyina» jurnali muallifi.$$),
(NULL, (SELECT id FROM eras WHERE code = 'jadidlar'),
 $$Toshkent jadidlarining yetakchisi kim edi?$$,
 $$["Behbudiy", "Fitrat", "Cho'lpon", "Munavvarqori Abdurashidxonov"]$$, 3,
 $$Munavvarqori Abdurashidxonov Toshkentda yangi usul maktablari ochgan va jadidlar harakatiga boshchilik qilgan.$$),
(NULL, (SELECT id FROM eras WHERE code = 'jadidlar'),
 $$Abdulla Avloniyning maktablar uchun yozgan mashhur asari qaysi?$$,
 $$["«Turkiy guliston yoxud axloq»", "«Padarkush»", "«O'tkan kunlar»", "«Munozara»"]$$, 0,
 $$Avloniyning «Turkiy guliston yoxud axloq» darsligi bolalarga odob-axloqni o'rgatgan.$$),
(NULL, (SELECT id FROM eras WHERE code = 'jadidlar'),
 $$Birinchi o'zbek gazetalaridan «Taraqqiy» qachon chiqa boshlagan?$$,
 $$["1865-yilda", "1906-yilda", "1917-yilda", "1924-yilda"]$$, 1,
 $$«Taraqqiy» gazetasi 1906-yilda Toshkentda chiqa boshlagan — milliy matbuotning boshlanishi.$$),
(NULL, (SELECT id FROM eras WHERE code = 'jadidlar'),
 $$«Munozara» asarining muallifi, yirik jadid olimi kim?$$,
 $$["Avloniy", "Behbudiy", "Abdurauf Fitrat", "Hamza"]$$, 2,
 $$Abdurauf Fitrat «Munozara» asarida eski maktab va jamiyatni isloh qilish g'oyalarini ilgari surgan.$$),
(NULL, (SELECT id FROM eras WHERE code = 'jadidlar'),
 $$«Kecha va kunduz» romanining muallifi kim?$$,
 $$["Qodiriy", "Behbudiy", "Fitrat", "Cho'lpon"]$$, 3,
 $$Abdulhamid Cho'lpon — jadid shoiri va yozuvchisi, «Kecha va kunduz» romani muallifi.$$);

-- ============ XX ASR (+8) ============

INSERT INTO quiz_questions (hero_id, era_id, question_uz, options, correct_index, explanation_uz) VALUES
(NULL, (SELECT id FROM eras WHERE code = 'xx-asr'),
 $$Turkiston muxtoriyati qachon e'lon qilingan?$$,
 $$["1917-yil noyabrda", "1905-yilda", "1924-yilda", "1936-yilda"]$$, 0,
 $$Turkiston muxtoriyati 1917-yil noyabrda Qo'qonda e'lon qilingan va bor-yo'g'i 72 kun yashagan.$$),
(NULL, (SELECT id FROM eras WHERE code = 'xx-asr'),
 $$O'zbekiston SSR qachon tashkil etilgan?$$,
 $$["1917-yilda", "1924-yilda", "1936-yilda", "1945-yilda"]$$, 1,
 $$1924-yilgi milliy-hududiy chegaralanish natijasida O'zbekiston SSR tashkil etilgan.$$),
(NULL, (SELECT id FROM eras WHERE code = 'xx-asr'),
 $$Ikkinchi jahon urushi yillarida O'zbekistonga nima evakuatsiya qilingan?$$,
 $$["Faqat oziq-ovqat", "Faqat harbiy texnika", "Sanoat korxonalari va minglab bolalar", "Hech narsa"]$$, 2,
 $$Urush yillarida O'zbekistonga yuzlab zavodlar va minglab yetim bolalar ko'chirilgan; xalqimiz ularni bag'riga olgan.$$),
(NULL, (SELECT id FROM eras WHERE code = 'xx-asr'),
 $$Urush yillarida 15 nafar yetim bolani asrab olgan toshkentlik oila qaysi?$$,
 $$["Rahimovlar", "Karimovlar", "Yusupovlar", "Shomahmudovlar"]$$, 3,
 $$Shoahmad Shomahmudov va Bahri opa turli millatga mansub 15 yetim bolani o'z farzandidek tarbiyalagan.$$),
(NULL, (SELECT id FROM eras WHERE code = 'xx-asr'),
 $$Sovet davrida O'zbekiston qishloq xo'jaligi asosan nimaga bo'ysundirilgan edi?$$,
 $$["Paxta yakkahokimligiga", "Baliqchilikka", "Uzumchilikka", "Chorvachilikka"]$$, 0,
 $$Paxta yakkahokimligi tuproq va suv resurslarining ayovsiz ishlatilishiga olib keldi.$$),
(NULL, (SELECT id FROM eras WHERE code = 'xx-asr'),
 $$O'zbek tiliga davlat tili maqomi qachon berilgan?$$,
 $$["1991-yil 31-avgustda", "1989-yil 21-oktabrda", "1992-yil 8-dekabrda", "1985-yilda"]$$, 1,
 $$Davlat tili to'g'risidagi qonun mustaqillikdan oldin — 1989-yil 21-oktabrda qabul qilingan.$$),
(NULL, (SELECT id FROM eras WHERE code = 'xx-asr'),
 $$Orol dengizi fojiasining asosiy sababi nima?$$,
 $$["Zilzilalar", "Iqlim sovishi", "Daryolar suvining sug'orishga olib ketilishi", "Vulqon otilishi"]$$, 2,
 $$Amudaryo va Sirdaryo suvlari paxta dalalarini sug'orishga sarflanib, dengizga yetib bormay qo'ygan.$$),
(NULL, (SELECT id FROM eras WHERE code = 'xx-asr'),
 $$1966-yilgi zilziladan keyin Toshkent qanday tiklangan?$$,
 $$["Tiklanmagan", "Faqat 50 yildan keyin tiklangan", "Aholi boshqa shaharga ko'chirilgan", "Butun mamlakat yordamida qayta qurilgan"]$$, 3,
 $$Zilziladan keyin Toshkent qisqa muddatda qayta qurilib, zamonaviy shaharga aylantirildi.$$);

-- ============ MUSTAQILLIK DAVRI (+8) ============

INSERT INTO quiz_questions (hero_id, era_id, question_uz, options, correct_index, explanation_uz) VALUES
(NULL, (SELECT id FROM eras WHERE code = 'mustaqillik'),
 $$Mustaqillik kuni qaysi sanada nishonlanadi?$$,
 $$["1-sentabrda", "31-avgustda", "8-dekabrda", "21-martda"]$$, 0,
 $$Mustaqillik 1991-yil 31-avgustda e'lon qilingan, bayram esa 1-sentabrda nishonlanadi.$$),
(NULL, (SELECT id FROM eras WHERE code = 'mustaqillik'),
 $$Milliy valyuta — so'm qachon muomalaga kiritilgan?$$,
 $$["1991-yil 1-sentabrda", "1994-yil 1-iyulda", "1992-yil 2-martda", "2000-yil 1-yanvarda"]$$, 1,
 $$O'zbekiston so'mi 1994-yil 1-iyuldan milliy valyuta sifatida muomalaga kiritilgan.$$),
(NULL, (SELECT id FROM eras WHERE code = 'mustaqillik'),
 $$O'zbekiston BMTga qachon a'zo bo'lgan?$$,
 $$["1991-yil 31-avgustda", "1994-yil 1-iyulda", "1992-yil 2-martda", "1993-yil 1-yanvarda"]$$, 2,
 $$O'zbekiston 1992-yil 2-martda Birlashgan Millatlar Tashkilotiga a'zo bo'lgan.$$),
(NULL, (SELECT id FROM eras WHERE code = 'mustaqillik'),
 $$O'zbekiston Respublikasining birinchi Prezidenti kim?$$,
 $$["Sharof Rashidov", "Shavkat Mirziyoyev", "Abdulla Oripov", "Islom Karimov"]$$, 3,
 $$Islom Karimov — O'zbekiston Respublikasining birinchi Prezidenti (1991–2016).$$),
(NULL, (SELECT id FROM eras WHERE code = 'mustaqillik'),
 $$O'zbekiston davlat bayrog'i qachon qabul qilingan?$$,
 $$["1991-yil 18-noyabrda", "1992-yil 2-iyulda", "1993-yil 10-dekabrda", "1994-yil 1-iyulda"]$$, 0,
 $$Davlat bayrog'i mustaqillikdan ko'p o'tmay — 1991-yil 18-noyabrda qabul qilingan.$$),
(NULL, (SELECT id FROM eras WHERE code = 'mustaqillik'),
 $$O'zbekiston davlat gerbi qachon qabul qilingan?$$,
 $$["1991-yil 1-sentabrda", "1992-yil 2-iyulda", "1990-yil 20-iyunda", "1994-yil 1-iyulda"]$$, 1,
 $$Davlat gerbi 1992-yil 2-iyulda qabul qilingan; markazida baxt qushi — Humo tasvirlangan.$$),
(NULL, (SELECT id FROM eras WHERE code = 'mustaqillik'),
 $$Davlat madhiyasi musiqasining muallifi kim?$$,
 $$["Yunus Rajabiy", "Abdulla Oripov", "Mutal Burhonov", "Erkin Vohidov"]$$, 2,
 $$Madhiya musiqasi — Mutal Burhonov, matni — Abdulla Oripov qalamiga mansub.$$),
(NULL, (SELECT id FROM eras WHERE code = 'mustaqillik'),
 $$Bayrog'imizdagi oq rang nimani anglatadi?$$,
 $$["Boylikni", "Kuchni", "Jasoratni", "Tinchlik va poklikni"]$$, 3,
 $$Oq rang — tinchlik va poklik ramzi; ko'k — osmon va suv, yashil — tabiat, qizil chiziqlar — hayot kuchi.$$);
