-- Tirik tarix: barcha davrlar uchun fakt kartochkalari (M5 kutubxona).
-- Har bir davrga 8 tadan kartochka; barcha faktlar manbalarga tayanadi,
-- metodist tekshiruvi shart. Kartochkalar davr testlari va kutubxonani oziqlantiradi.

-- ============ QADIMGI DAVR ============

INSERT INTO fact_cards (era_id, topic_uz, fact_uz, keywords, source) VALUES
((SELECT id FROM eras WHERE code = 'qadimgi'), $$Eng qadimgi manzilgohlar$$,
 $$Farg'ona vodiysidagi Selung'ur g'orida qariyb bir million yil avval qadimgi odamlar yashagan. Surxondaryodagi Teshiktosh g'oridan esa neandertal bolasining qoldiqlari topilgan — bu kashfiyot butun dunyoga mashhur bo'lgan.$$,
 $$["selungur", "teshiktosh", "gor", "qadimgi odam", "neandertal"]$$,
 $$«O'zbekiston tarixi» 6-sinf darsligi$$),
((SELECT id FROM eras WHERE code = 'qadimgi'), $$«Avesto»$$,
 $$«Avesto» — zardushtiylik dinining muqaddas kitobi, bundan qariyb 2700 yil avval yaratila boshlagan. Ko'plab olimlar uning eng qadimgi qismlari Xorazm vohasida vujudga kelgan deb hisoblaydi. 2001-yilda «Avesto»ning 2700 yilligi keng nishonlangan.$$,
 $$["avesto", "kitob", "zardushtiylik", "xorazm", "muqaddas"]$$,
 $$O'zbekiston milliy ensiklopediyasi$$),
((SELECT id FROM eras WHERE code = 'qadimgi'), $$Ilk davlatlar$$,
 $$Hududimizdagi eng qadimgi davlatlar — Katta Xorazm, Baqtriya va So'g'diyona. Ular mil. avv. I ming yillikda vujudga kelgan: Baqtriya — Amudaryoning yuqori oqimida, So'g'diyona — Zarafshon vodiysida, Xorazm — Amudaryoning quyi oqimida.$$,
 $$["xorazm", "baqtriya", "sogdiyona", "davlat", "qadimgi"]$$,
 $$«O'zbekiston tarixi» 6-sinf darsligi$$),
((SELECT id FROM eras WHERE code = 'qadimgi'), $$To'maris jasorati$$,
 $$To'maris — massagetlar malikasi. Mil. avv. VI asrda fors shohi Kir II massagetlar yurtiga bostirib kirganda, To'maris boshchiligidagi jangchilar bosqinchilarni tor-mor etgan. Uning nomi vatan himoyasi ramziga aylangan.$$,
 $$["tomaris", "malika", "massaget", "kir", "jasorat"]$$,
 $$O'zbekiston milliy ensiklopediyasi$$),
((SELECT id FROM eras WHERE code = 'qadimgi'), $$Shiroq jasorati$$,
 $$Shiroq — sak cho'poni. Fors shohi Doro I qo'shini yurtimizga bostirib kirganda, Shiroq yo'l ko'rsatuvchi qiyofasida dushman qo'shinini ataylab suvsiz sahroga boshlab borgan va vatani uchun jonini fido qilgan.$$,
 $$["shiroq", "chopon", "sak", "doro", "sahro", "fido"]$$,
 $$«O'zbekiston tarixi» 6-sinf darsligi$$),
((SELECT id FROM eras WHERE code = 'qadimgi'), $$Bronza davri madaniyati$$,
 $$Surxondaryodagi Sopollitepa va Jarqo'ton yodgorliklari bronza davriga oid. U yerda mil. avv. II ming yillikda dehqonchilik, hunarmandchilik va me'morlik yuksak darajada rivojlangan — bu o'lkamizdagi ilk shaharsozlik madaniyatining namunasi.$$,
 $$["sopollitepa", "jarqoton", "bronza", "shahar", "dehqonchilik"]$$,
 $$O'zbekiston milliy ensiklopediyasi$$),
((SELECT id FROM eras WHERE code = 'qadimgi'), $$Zardushtiylik dini$$,
 $$Zardushtiylik — payg'ambar Zardusht asos solgan qadimgi din. Unda olov, suv, tuproq va havo muqaddas sanalgan, ezgu fikr, ezgu so'z va ezgu amal bosh qoida bo'lgan. Navro'z bayramining ildizlari ham shu qadimgi davrga borib taqaladi.$$,
 $$["zardusht", "din", "olov", "ezgu", "navroz"]$$,
 $$O'zbekiston milliy ensiklopediyasi$$),
((SELECT id FROM eras WHERE code = 'qadimgi'), $$Qadimgi Xorazm qal'alari$$,
 $$Qadimgi Xorazmda Tuproqqal'a, Ayozqal'a, Jonbosqal'a kabi ulkan qal'alar qurilgan. Xorazmliklar cho'l o'rtasida murakkab sug'orish kanallari barpo etib, dehqonchilikni yuksak darajaga ko'targan.$$,
 $$["tuproqqala", "ayozqala", "qala", "sugorish", "kanal"]$$,
 $$O'zbekiston milliy ensiklopediyasi$$);

-- ============ ANTIK DAVR ============

INSERT INTO fact_cards (era_id, topic_uz, fact_uz, keywords, source) VALUES
((SELECT id FROM eras WHERE code = 'antik'), $$Iskandar yurishi$$,
 $$Iskandar Maqduniy (Aleksandr Makedonskiy) mil. avv. 329-yilda Movarounnahrga bostirib kirgan. Xalqimiz So'g'd sarkardasi Spitamen boshchiligida uch yil davomida bosqinchilarga qattiq qarshilik ko'rsatgan.$$,
 $$["iskandar", "aleksandr", "spitamen", "yurish", "qarshilik"]$$,
 $$«O'zbekiston tarixi» 6-sinf darsligi$$),
((SELECT id FROM eras WHERE code = 'antik'), $$Yunon-Baqtriya davlati$$,
 $$Mil. avv. III asr o'rtalarida Yunon-Baqtriya davlati tashkil topgan. Bu davrda yunon va mahalliy madaniyatlar qo'shilib, o'ziga xos san'at — ellinizm madaniyati vujudga kelgan.$$,
 $$["yunon", "baqtriya", "ellinizm", "davlat"]$$,
 $$O'zbekiston milliy ensiklopediyasi$$),
((SELECT id FROM eras WHERE code = 'antik'), $$Qang' davlati$$,
 $$Mil. avv. III asrda Sirdaryoning o'rta oqimida Qang' (Kanguy) davlati vujudga kelgan. U o'z davrining qudratli davlatlaridan bo'lib, dehqonchilik, chorvachilik va Ipak yo'li savdosidan boyigan.$$,
 $$["qang", "kanguy", "sirdaryo", "davlat"]$$,
 $$«O'zbekiston tarixi» 6-sinf darsligi$$),
((SELECT id FROM eras WHERE code = 'antik'), $$Dovon davlati$$,
 $$Farg'ona vodiysida qadimda Dovon davlati joylashgan. U «samoviy arg'umoqlar» deb nom olgan zotdor otlari bilan mashhur bo'lgan — Xitoy imperatorlari bu otlarga ega bo'lish uchun harbiy yurishlar ham uyushtirgan.$$,
 $$["dovon", "fargona", "ot", "argumoq"]$$,
 $$O'zbekiston milliy ensiklopediyasi$$),
((SELECT id FROM eras WHERE code = 'antik'), $$Kushon saltanati$$,
 $$Milodiy I–III asrlarda hududimiz qudratli Kushon saltanati tarkibida bo'lgan. Kanishka davrida saltanat eng yuksak cho'qqiga chiqqan; Termiz atrofidagi Fayoztepa va Qoratepa ibodatxonalari buddizm keng tarqalganidan guvohlik beradi.$$,
 $$["kushon", "kanishka", "buddizm", "fayoztepa", "termiz"]$$,
 $$O'zbekiston milliy ensiklopediyasi$$),
((SELECT id FROM eras WHERE code = 'antik'), $$Buyuk ipak yo'li$$,
 $$Buyuk ipak yo'li Xitoyni O'rta yer dengizi mamlakatlari bilan bog'lagan va yurtimiz orqali o'tgan. Karvonlar ipak, ziravorlar, shisha va qimmatbaho toshlarni tashigan; yo'l bo'ylab shaharlar — Samarqand, Buxoro, Termiz gullab-yashnagan.$$,
 $$["ipak yoli", "karvon", "savdo", "xitoy", "yol"]$$,
 $$«O'zbekiston tarixi» 6-sinf darsligi$$),
((SELECT id FROM eras WHERE code = 'antik'), $$So'g'd savdogarlari$$,
 $$So'g'd savdogarlari Ipak yo'lining asosiy vositachilari edi. Ular Xitoydan Vizantiyagacha savdo shoxobchalari ochgan, so'g'd tili esa yo'lning xalqaro savdo tiliga aylangan.$$,
 $$["sogd", "savdogar", "til", "savdo"]$$,
 $$O'zbekiston milliy ensiklopediyasi$$),
((SELECT id FROM eras WHERE code = 'antik'), $$Afrosiyob$$,
 $$Afrosiyob — qadimgi Samarqandning o'rni. U yerdan topilgan mashhur devoriy suratlarda elchilar qabuli, bayram marosimlari va o'sha davr kiyimlari tasvirlangan — bu suratlar antik shahar madaniyatining noyob guvohi.$$,
 $$["afrosiyob", "samarqand", "surat", "devoriy"]$$,
 $$O'zbekiston milliy ensiklopediyasi$$);

-- ============ ARABLAR DAVRI ============

INSERT INTO fact_cards (era_id, topic_uz, fact_uz, keywords, source) VALUES
((SELECT id FROM eras WHERE code = 'arab'), $$Arablar istilosi$$,
 $$Arab sarkardasi Qutayba ibn Muslim 709–712-yillarda Buxoro, Samarqand va Xorazmni bosib olgan. Istilo bilan birga islom dini va arab yozuvi kirib kelib, o'lka madaniyatiga chuqur ta'sir ko'rsatgan.$$,
 $$["qutayba", "istilo", "islom", "arab"]$$,
 $$«O'zbekiston tarixi» 7-sinf darsligi$$),
((SELECT id FROM eras WHERE code = 'arab'), $$Muqanna qo'zg'oloni$$,
 $$VIII asrning 70-yillarida Muqanna boshchiligidagi «oq kiyimlilar» qo'zg'oloni arab xalifaligi zulmiga qarshi ko'tarilgan. Qo'zg'olon o'n yildan ortiq davom etib, xalqning erk uchun kurashi ramziga aylangan.$$,
 $$["muqanna", "qozgolon", "oq kiyimlilar", "xalifalik"]$$,
 $$O'zbekiston milliy ensiklopediyasi$$),
((SELECT id FROM eras WHERE code = 'arab'), $$Bayt ul-hikma va olimlarimiz$$,
 $$IX asrda Bag'doddagi «Bayt ul-hikma» (Donishmandlik uyi)da Movarounnahr va Xorazmdan chiqqan olimlar — al-Xorazmiy va al-Farg'oniy jahon faniga ulkan hissa qo'shgan. Al-Xorazmiy algebra faniga asos solgan, nomi «algoritm» so'zida abadiylashgan.$$,
 $$["bayt ul-hikma", "xorazmiy", "fargoniy", "bagdod", "algebra", "algoritm"]$$,
 $$O'zbekiston milliy ensiklopediyasi$$),
((SELECT id FROM eras WHERE code = 'arab'), $$Ahmad al-Farg'oniy$$,
 $$Ahmad al-Farg'oniy — buyuk astronom. Uning «Astronomiya asoslari» kitobi Yevropada «Alfraganus» nomi bilan asrlar davomida darslik bo'lgan. U Misrda Nil daryosi suvini o'lchaydigan mashhur inshoot — nilometrni ham loyihalagan.$$,
 $$["fargoniy", "alfraganus", "astronomiya", "nil"]$$,
 $$O'zbekiston milliy ensiklopediyasi$$),
((SELECT id FROM eras WHERE code = 'arab'), $$Hadis ilmi sultonlari$$,
 $$Vatandoshlarimiz Imom al-Buxoriy va Imom at-Termiziy hadis ilmining eng buyuk olimlari sanaladi. Al-Buxoriyning «Al-jome as-sahih» to'plami islom olamida Qur'ondan keyingi eng ishonchli kitob deb e'tirof etilgan.$$,
 $$["buxoriy", "termiziy", "hadis", "sahih"]$$,
 $$O'zbekiston milliy ensiklopediyasi$$),
((SELECT id FROM eras WHERE code = 'arab'), $$Somoniylar davlati$$,
 $$IX–X asrlarda Somoniylar davlati poytaxti Buxoro yirik ilm-fan va madaniyat markaziga aylangan. Bu davrda mahalliy davlatchilik qayta tiklanib, fors-tojik adabiyoti (Rudakiy) va ilm-fan ravnaq topgan.$$,
 $$["somoniylar", "buxoro", "davlat", "rudakiy"]$$,
 $$«O'zbekiston tarixi» 7-sinf darsligi$$),
((SELECT id FROM eras WHERE code = 'arab'), $$Ibn Sino va Beruniy$$,
 $$X–XI asrlar qomusiy olimlar davri: Ibn Sino «Tib qonunlari» bilan jahon tibbiyotiga asos solgan, Abu Rayhon Beruniy esa «Hindiston» va «Qadimgi xalqlardan qolgan yodgorliklar» asarlarida tarix, geografiya va astronomiyani boyitgan.$$,
 $$["ibn sino", "beruniy", "tib", "hindiston", "olim"]$$,
 $$O'zbekiston milliy ensiklopediyasi$$),
((SELECT id FROM eras WHERE code = 'arab'), $$Abu Nasr Forobiy$$,
 $$Abu Nasr Forobiy falsafa, mantiq va musiqa ilmiga ulkan hissa qo'shgani uchun «Ikkinchi muallim» (Arastudan keyin) deb ulug'langan. Uning «Fozil odamlar shahri» asari adolatli jamiyat haqidagi orzularni ifodalaydi.$$,
 $$["forobiy", "ikkinchi muallim", "falsafa", "fozil"]$$,
 $$O'zbekiston milliy ensiklopediyasi$$);

-- ============ TEMURIYLAR DAVRI ============

INSERT INTO fact_cards (era_id, topic_uz, fact_uz, keywords, source) VALUES
((SELECT id FROM eras WHERE code = 'temuriylar'), $$Markazlashgan davlat$$,
 $$1370-yilda Amir Temur Movarounnahrda markazlashgan davlatga asos soldi. Uning «Kuch — adolatda» shiori davlat boshqaruvining bosh qoidasi edi; «Temur tuzuklari»da esa boshqaruv qonun-qoidalari bayon etilgan.$$,
 $$["temur", "davlat", "1370", "adolat", "tuzuklar"]$$,
 $$«O'zbekiston tarixi» 7-sinf darsligi$$),
((SELECT id FROM eras WHERE code = 'temuriylar'), $$Poytaxt Samarqand$$,
 $$Amir Temur Samarqandni dunyoning eng go'zal shahriga aylantirishga intildi: Bibixonim jome masjidi, Go'ri Amir maqbarasi, Shohi Zinda ansambli shu davrda qad rostlagan. Shahrisabzda esa ulug'vor Oqsaroy qurilgan.$$,
 $$["samarqand", "bibixonim", "gori amir", "oqsaroy", "memorlik"]$$,
 $$O'zbekiston milliy ensiklopediyasi$$),
((SELECT id FROM eras WHERE code = 'temuriylar'), $$Ulug'bek rasadxonasi$$,
 $$Mirzo Ulug'bek 1428–1429-yillarda Samarqandda ulkan rasadxona qurdirgan. U yerda tuzilgan «Ziji jadidi Ko'ragoniy» jadvalida 1018 yulduzning o'rni hayratlanarli aniqlikda ko'rsatilgan — bu asar Yevropada ham nashr etilgan.$$,
 $$["rasadxona", "ulugbek", "zij", "yulduz", "astronomiya"]$$,
 $$O'zbekiston milliy ensiklopediyasi$$),
((SELECT id FROM eras WHERE code = 'temuriylar'), $$Ulug'bek madrasalari$$,
 $$Ulug'bek Samarqand, Buxoro va G'ijduvonda madrasalar qurdirgan. Buxoro madrasasi darvozasiga «Bilim olish har bir muslim va muslima uchun farzdir» degan hikmat bitilgan — bu ilmga bo'lgan yuksak e'tiborning ramzi.$$,
 $$["madrasa", "bilim", "buxoro", "talim"]$$,
 $$«O'zbekiston tarixi» 7-sinf darsligi$$),
((SELECT id FROM eras WHERE code = 'temuriylar'), $$Navoiy va ona tili$$,
 $$Alisher Navoiy «Xamsa» va «Xazoyin ul-maoniy» asarlari bilan turkiy (eski o'zbek) tilini buyuk adabiyot tiliga aylantirdi. «Muhokamat ul-lug'atayn» asarida ona tilimizning boyligini fors tili bilan qiyoslab isbotlagan.$$,
 $$["navoiy", "xamsa", "til", "adabiyot", "muhokamat"]$$,
 $$O'zbekiston milliy ensiklopediyasi$$),
((SELECT id FROM eras WHERE code = 'temuriylar'), $$Hirot madaniy markazi$$,
 $$XV asr oxirida Husayn Boyqaro hukmronligidagi Hirot Sharqning madaniy poytaxtiga aylandi: bu yerda Navoiy ijod qildi, Kamoliddin Behzod esa miniatyura san'atini shu qadar yuksaltirdiki, uni «Sharq Rafaeli» deb atashgan.$$,
 $$["hirot", "boyqaro", "behzod", "miniatyura"]$$,
 $$O'zbekiston milliy ensiklopediyasi$$),
((SELECT id FROM eras WHERE code = 'temuriylar'), $$Sharq Uyg'onish davri$$,
 $$Temuriylar davri «Sharq Uyg'onish davri» (Temuriylar Renessansi) deb ataladi: astronomiya, matematika, tarix, adabiyot, xattotlik va me'morlik misli ko'rilmagan darajada rivojlanib, jahon madaniyatiga ulkan hissa qo'shgan.$$,
 $$["uygonish", "renessans", "ilm", "madaniyat"]$$,
 $$«O'zbekiston tarixi» 7-sinf darsligi$$),
((SELECT id FROM eras WHERE code = 'temuriylar'), $$Bobur va boburiylar$$,
 $$Temuriy shahzoda Zahiriddin Muhammad Bobur 1526-yilda Hindistonda boburiylar saltanatiga asos soldi. Uning «Boburnoma» asari — ona tilimizdagi birinchi memuar; boburiylar qurdirgan Tojmahal esa jahon me'morligining durdonasi.$$,
 $$["bobur", "boburnoma", "hindiston", "tojmahal"]$$,
 $$O'zbekiston milliy ensiklopediyasi$$);

-- ============ XONLIKLAR DAVRI ============

INSERT INTO fact_cards (era_id, topic_uz, fact_uz, keywords, source) VALUES
((SELECT id FROM eras WHERE code = 'xonliklar'), $$Shayboniylar davri$$,
 $$1500–1506-yillarda Muhammad Shayboniyxon temuriylar davlatini egallab, Movarounnahrda shayboniylar sulolasi hukmronligini o'rnatdi. XVI asrda Buxoro xonligi mintaqaning yirik davlatiga aylandi.$$,
 $$["shayboniy", "sulola", "buxoro", "xonlik"]$$,
 $$«O'zbekiston tarixi» 8-sinf darsligi$$),
((SELECT id FROM eras WHERE code = 'xonliklar'), $$Uch davlat$$,
 $$XVIII–XIX asrlarda hududimizda uchta davlat mavjud edi: Buxoro amirligi, Xiva xonligi va Qo'qon xonligi. Ular o'rtasidagi tez-tez urushlar o'lkani zaiflashtirib, chet el istilosiga zamin yaratdi.$$,
 $$["buxoro", "xiva", "qoqon", "uch davlat", "amirlik"]$$,
 $$«O'zbekiston tarixi» 8-sinf darsligi$$),
((SELECT id FROM eras WHERE code = 'xonliklar'), $$Xon-tarixchi Abulg'oziy$$,
 $$Xiva xoni Abulg'oziy Bahodirxon (1603–1664) nafaqat davlat arbobi, balki olim ham edi: uning «Shajarayi turk» asari turkiy xalqlar tarixini o'rganishda muhim manba sanaladi.$$,
 $$["abulgoziy", "shajarayi turk", "xiva", "tarixchi"]$$,
 $$O'zbekiston milliy ensiklopediyasi$$),
((SELECT id FROM eras WHERE code = 'xonliklar'), $$Ichan-qal'a$$,
 $$Xivaning Ichan-qal'a majmuasi — minoralar, madrasalar va saroylar bir butun saqlangan noyob shahar-yodgorlik. U O'zbekistonda birinchi bo'lib YUNESKOning Jahon merosi ro'yxatiga kiritilgan.$$,
 $$["ichan-qala", "xiva", "yunesko", "yodgorlik"]$$,
 $$O'zbekiston milliy ensiklopediyasi$$),
((SELECT id FROM eras WHERE code = 'xonliklar'), $$Buxoro me'morligi$$,
 $$Xonliklar davrida Buxoroda Labi hovuz ansambli, Chor minor va ko'plab savdo gumbazlari qurilgan. XII asrdan qad rostlab turgan Kalon minorasi esa shaharning ramzi bo'lib qolgan.$$,
 $$["labi hovuz", "chor minor", "kalon", "buxoro", "memorlik"]$$,
 $$O'zbekiston milliy ensiklopediyasi$$),
((SELECT id FROM eras WHERE code = 'xonliklar'), $$Mumtoz adabiyot$$,
 $$Xonliklar davrida xalq dardini kuylagan Boborahim Mashrab, Xorazmda ijod qilgan Munis va Ogahiy, Qo'qonda esa Amiriy va Furqat kabi shoirlar mumtoz adabiyotimizni boyitgan.$$,
 $$["mashrab", "ogahiy", "munis", "shoir", "adabiyot"]$$,
 $$«O'zbek adabiyoti tarixi»$$),
((SELECT id FROM eras WHERE code = 'xonliklar'), $$Shoiralar$$,
 $$Qo'qon xoni Umarxonning rafiqasi Nodira va uning zamondoshi Uvaysiy — o'zbek mumtoz adabiyotining buyuk shoiralari. Nodira davlat ishlarida ham faol qatnashib, madaniyat homiysi bo'lgan.$$,
 $$["nodira", "uvaysiy", "shoira", "qoqon"]$$,
 $$O'zbekiston milliy ensiklopediyasi$$),
((SELECT id FROM eras WHERE code = 'xonliklar'), $$Hunarmandchilik va savdo$$,
 $$Xonliklar davrida Marg'ilon atlasi, Rishton kulolchiligi, Buxoro zardo'zligi kabi hunarmandchilik maktablari shakllangan. Bozorlar va karvonsaroylar shaharlar hayotining markazi edi.$$,
 $$["atlas", "kulolchilik", "zardozlik", "hunarmand", "bozor"]$$,
 $$O'zbekiston milliy ensiklopediyasi$$);

-- ============ JADIDLAR DAVRI ============

INSERT INTO fact_cards (era_id, topic_uz, fact_uz, keywords, source) VALUES
((SELECT id FROM eras WHERE code = 'jadidlar'), $$Rossiya istilosi$$,
 $$1865-yilda Toshkent Rossiya imperiyasi tomonidan bosib olindi, 1867-yilda Turkiston general-gubernatorligi tuzildi. Buxoro amirligi va Xiva xonligi esa Rossiyaga qaram davlatlarga aylantirildi.$$,
 $$["istilo", "toshkent", "1865", "gubernatorlik", "rossiya"]$$,
 $$«O'zbekiston tarixi» 9-sinf darsligi$$),
((SELECT id FROM eras WHERE code = 'jadidlar'), $$Jadidchilik harakati$$,
 $$Jadidchilik («jadid» — yangi) — mustamlaka sharoitida millatni ma'rifat orqali uyg'otishga qaratilgan harakat. Jadidlar yangi usul maktablari, matbuot va teatr orqali xalqni ilmli qilishga intildi.$$,
 $$["jadid", "marifat", "harakat", "yangilik"]$$,
 $$O'zbekiston milliy ensiklopediyasi$$),
((SELECT id FROM eras WHERE code = 'jadidlar'), $$Yangi usul maktablari$$,
 $$Usuli jadid maktablarida bolalar eski usuldagidan ancha tez — bir necha oyda savod chiqargan, jug'rofiya, hisob va tarix kabi dunyoviy fanlarni ham o'rgangan. Bu maktablar milliy uyg'onishning beshigi bo'ldi.$$,
 $$["maktab", "usuli jadid", "savod", "talim"]$$,
 $$«O'zbekiston tarixi» 9-sinf darsligi$$),
((SELECT id FROM eras WHERE code = 'jadidlar'), $$Mahmudxo'ja Behbudiy$$,
 $$Samarqandlik Mahmudxo'ja Behbudiy — jadidlar yetakchisi, birinchi o'zbek dramasi «Padarkush» muallifi va «Oyina» jurnali noshiri. U «Haq olinur, berilmas!» degan mashhur so'zlari bilan tarixda qolgan.$$,
 $$["behbudiy", "padarkush", "oyina", "samarqand"]$$,
 $$O'zbekiston milliy ensiklopediyasi$$),
((SELECT id FROM eras WHERE code = 'jadidlar'), $$Munavvarqori va Avloniy$$,
 $$Toshkentda Munavvarqori Abdurashidxonov yangi usul maktablari tarmog'ini yaratib, «Adibi avval» darsligini yozgan. Abdulla Avloniy esa «Turkiy guliston yoxud axloq» kitobi va teatr truppasi bilan ma'rifat tarqatgan.$$,
 $$["munavvarqori", "avloniy", "darslik", "teatr", "toshkent"]$$,
 $$O'zbekiston milliy ensiklopediyasi$$),
((SELECT id FROM eras WHERE code = 'jadidlar'), $$Milliy matbuot$$,
 $$1906-yilda birinchi o'zbek gazetalaridan «Taraqqiy» chiqa boshladi. Keyinroq «Sadoi Turkiston», «Samarqand» va boshqa nashrlar xalqqa dunyodagi voqealarni yetkazib, milliy ongni o'stirdi.$$,
 $$["taraqqiy", "gazeta", "matbuot", "1906"]$$,
 $$O'zbekiston milliy ensiklopediyasi$$),
((SELECT id FROM eras WHERE code = 'jadidlar'), $$Fitrat va Cho'lpon$$,
 $$Abdurauf Fitrat «Munozara» asarida jamiyatni isloh qilish g'oyalarini ilgari surdi, Abdulhamid Cho'lpon esa «Kecha va kunduz» romani hamda erk haqidagi she'rlari bilan yangi o'zbek adabiyotiga asos soldi.$$,
 $$["fitrat", "cholpon", "munozara", "adabiyot"]$$,
 $$«O'zbek adabiyoti tarixi»$$),
((SELECT id FROM eras WHERE code = 'jadidlar'), $$Jadidlar merosi$$,
 $$Jadidlar millat kelajagini bilimli avlodda ko'rdi: «Najot — ta'limda» ularning bosh g'oyasi edi. Ularning ma'rifat yo'lidagi jasorati bugungi mustaqil O'zbekistonda yuksak qadrlanadi.$$,
 $$["meros", "najot", "talim", "goya"]$$,
 $$«O'zbekiston tarixi» 9-sinf darsligi$$);

-- ============ XX ASR ============

INSERT INTO fact_cards (era_id, topic_uz, fact_uz, keywords, source) VALUES
((SELECT id FROM eras WHERE code = 'xx-asr'), $$Turkiston muxtoriyati$$,
 $$1917-yil noyabrda Qo'qonda Turkiston muxtoriyati e'lon qilindi — bu xalqimizning o'z davlatchiligini tiklash yo'lidagi ilk urinishi edi. Muxtoriyat bor-yo'g'i 72 kun yashab, sovet qo'shinlari tomonidan qonga botirildi.$$,
 $$["muxtoriyat", "qoqon", "1917", "72 kun"]$$,
 $$«O'zbekiston tarixi» 10-sinf darsligi$$),
((SELECT id FROM eras WHERE code = 'xx-asr'), $$O'zbekiston SSR$$,
 $$1924-yilgi milliy-hududiy chegaralanish natijasida O'zbekiston SSR tashkil etildi. Poytaxt dastlab Samarqand bo'lib, 1930-yilda Toshkentga ko'chirildi.$$,
 $$["ozssr", "1924", "chegaralanish", "poytaxt"]$$,
 $$«O'zbekiston tarixi» 10-sinf darsligi$$),
((SELECT id FROM eras WHERE code = 'xx-asr'), $$Qatag'on qurbonlari$$,
 $$1937–1938-yillardagi qatag'onda millatning eng yorqin farzandlari — Abdulla Qodiriy, Cho'lpon, Fitrat va minglab yurtdoshlarimiz otib tashlandi. Ularning xotirasi 31-avgust — Qatag'on qurbonlarini yod etish kunida ulug'lanadi.$$,
 $$["qatagon", "qodiriy", "1937", "qurbon", "xotira"]$$,
 $$O'zbekiston milliy ensiklopediyasi$$),
((SELECT id FROM eras WHERE code = 'xx-asr'), $$Urush yillarida O'zbekiston$$,
 $$Ikkinchi jahon urushida 1,5 milliondan ortiq o'zbekistonlik frontga safarbar etildi, yuz minglab yurtdoshimiz halok bo'ldi. O'zbekistonga yuzlab zavodlar va minglab yetim bolalar evakuatsiya qilindi — Shomahmudovlar oilasi 15 yetimni o'z bag'riga oldi.$$,
 $$["urush", "front", "evakuatsiya", "shomahmudov", "yetim"]$$,
 $$«O'zbekiston tarixi» 10-sinf darsligi$$),
((SELECT id FROM eras WHERE code = 'xx-asr'), $$Paxta yakkahokimligi va Orol$$,
 $$Sovet davrida O'zbekiston qishloq xo'jaligi paxta yakkahokimligiga bo'ysundirildi. Amudaryo va Sirdaryo suvlari dalalarga burib yuborilgani oqibatida Orol dengizi quriy boshladi — bu XX asrning eng yirik ekologik fojialaridan biridir.$$,
 $$["paxta", "orol", "ekologiya", "fojia", "dengiz"]$$,
 $$O'zbekiston milliy ensiklopediyasi$$),
((SELECT id FROM eras WHERE code = 'xx-asr'), $$Toshkent zilzilasi$$,
 $$1966-yil 26-aprelda Toshkentda kuchli zilzila yuz berib, yuz minglab kishi boshpanasiz qoldi. Shahar qisqa muddatda qayta qurilib, zamonaviy keng ko'chalar va yangi mavzelar barpo etildi.$$,
 $$["zilzila", "1966", "toshkent", "qayta qurish"]$$,
 $$O'zbekiston milliy ensiklopediyasi$$),
((SELECT id FROM eras WHERE code = 'xx-asr'), $$XX asr adabiyoti$$,
 $$Og'ir sinovlarga qaramay XX asrda o'zbek madaniyati rivojlandi: Oybek «Navoiy» romanini, G'afur G'ulom «Shum bola»ni yaratdi, Zulfiya she'riyati esa millionlab kitobxonlar qalbidan joy oldi.$$,
 $$["oybek", "gafur gulom", "zulfiya", "adabiyot", "shum bola"]$$,
 $$«O'zbek adabiyoti tarixi»$$),
((SELECT id FROM eras WHERE code = 'xx-asr'), $$Mustaqillik sari$$,
 $$1989-yil 21-oktabrda o'zbek tiliga davlat tili maqomi berildi — bu mustaqillik yo'lidagi muhim qadam edi. 1991-yil avgustiga kelib O'zbekiston o'z mustaqilligini e'lon qilishga tayyor bo'ldi.$$,
 $$["til", "1989", "davlat tili", "mustaqillik sari"]$$,
 $$«O'zbekiston tarixi» 10-sinf darsligi$$);

-- ============ MUSTAQILLIK DAVRI ============

INSERT INTO fact_cards (era_id, topic_uz, fact_uz, keywords, source) VALUES
((SELECT id FROM eras WHERE code = 'mustaqillik'), $$Mustaqillik e'loni$$,
 $$1991-yil 31-avgustda O'zbekiston davlat mustaqilligi e'lon qilindi; 1-sentabr Mustaqillik kuni sifatida nishonlanadi. Shu bilan xalqimiz tarixida yangi davr boshlandi.$$,
 $$["mustaqillik", "31-avgust", "1-sentabr", "elon"]$$,
 $$«O'zbekiston tarixi» 11-sinf darsligi$$),
((SELECT id FROM eras WHERE code = 'mustaqillik'), $$Konstitutsiya$$,
 $$1992-yil 8-dekabrda O'zbekiston Respublikasining Konstitutsiyasi qabul qilindi. Unda inson huquqlari, so'z erkinligi va qonun ustuvorligi davlatning oliy qadriyatlari deb belgilangan.$$,
 $$["konstitutsiya", "8-dekabr", "qonun", "huquq"]$$,
 $$O'zbekiston Respublikasi Konstitutsiyasi$$),
((SELECT id FROM eras WHERE code = 'mustaqillik'), $$Davlat ramzlari$$,
 $$Davlat bayrog'i 1991-yil 18-noyabrda, gerb 1992-yil 2-iyulda, madhiya 1992-yil 10-dekabrda qabul qilingan. Gerb markazida baxt va erk ramzi — afsonaviy Humo qushi tasvirlangan.$$,
 $$["bayroq", "gerb", "madhiya", "humo", "ramz"]$$,
 $$O'zbekiston milliy ensiklopediyasi$$),
((SELECT id FROM eras WHERE code = 'mustaqillik'), $$Bayroq ranglari$$,
 $$Bayrog'imizdagi ko'k rang — osmon va suv, oq — tinchlik va poklik, yashil — tabiat va yangilanish ramzi; qizil chiziqlar hayot kuchini anglatadi. Yarim oy va 12 yulduz esa xalqimizning qadimiy taqvim an'analari bilan bog'liq.$$,
 $$["bayroq", "rang", "yulduz", "yarim oy"]$$,
 $$O'zbekiston milliy ensiklopediyasi$$),
((SELECT id FROM eras WHERE code = 'mustaqillik'), $$Jahon hamjamiyatida$$,
 $$1992-yil 2-martda O'zbekiston Birlashgan Millatlar Tashkilotiga a'zo bo'ldi. Bugun mamlakatimizni dunyoning deyarli barcha davlatlari tan olgan va u xalqaro tashkilotlarda faol qatnashadi.$$,
 $$["bmt", "2-mart", "jahon", "azo"]$$,
 $$«O'zbekiston tarixi» 11-sinf darsligi$$),
((SELECT id FROM eras WHERE code = 'mustaqillik'), $$Milliy valyuta$$,
 $$1994-yil 1-iyulda milliy valyutamiz — so'm muomalaga kiritildi. O'z pulига ega bo'lish davlat mustaqilligining muhim belgilaridan biridir.$$,
 $$["som", "valyuta", "1994", "pul"]$$,
 $$O'zbekiston milliy ensiklopediyasi$$),
((SELECT id FROM eras WHERE code = 'mustaqillik'), $$Qadriyatlar tiklanishi$$,
 $$Mustaqillik yillarida Navro'z bayrami qayta tiklandi, Amir Temur, Ulug'bek va boburiylar merosi qadr topdi: 1996-yil «Amir Temur yili» deb e'lon qilinib, sohibqironning 660 yilligi keng nishonlandi.$$,
 $$["navroz", "qadriyat", "temur yili", "meros"]$$,
 $$O'zbekiston milliy ensiklopediyasi$$),
((SELECT id FROM eras WHERE code = 'mustaqillik'), $$Jahon merosi$$,
 $$Mustaqillik yillarida Ichan-qal'a, Buxoro, Shahrisabz va Samarqand tarixiy markazlari YUNESKOning Jahon merosi ro'yxatiga kiritildi — ota-bobolarimiz yaratgan boyliklar endi butun insoniyat mulki sanaladi.$$,
 $$["yunesko", "meros", "samarqand", "buxoro", "royxat"]$$,
 $$O'zbekiston milliy ensiklopediyasi$$);
